// <auto-generated />
using System;
using System.Collections.Generic;
using DataAccessLayer.EntityFramework.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DataAccessLayer.Migrations
{
    [DbContext(typeof(BaseDbContext))]
    [Migration("20260604131518_tablolar_olusturuldu")]
    partial class tablolar_olusturuldu
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Entity.CozumlemeSoruUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Asama")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<List<Dictionary<string, string>>>("SoruCevap")
                        .HasColumnType("jsonb");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("CozumlemeSoruUsers");
                });

            modelBuilder.Entity("Entity.Module", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .HasColumnType("text");

                    b.Property<string>("Address")
                        .HasColumnType("text");

                    b.Property<string>("Controller")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Icon")
                        .HasColumnType("text");

                    b.Property<int>("Menu")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<int>("ParentId")
                        .HasColumnType("integer");

                    b.Property<string>("Type")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.ToTable("Modules");

                    b.HasData(
                        new
                        {
                            Id = 21,
                            Action = "/kullanici_detay",
                            Address = "/User/Detail",
                            Controller = "User",
                            CreatedAt = new DateTime(2026, 6, 4, 16, 15, 18, 249, DateTimeKind.Local).AddTicks(7198),
                            Icon = "",
                            Menu = 0,
                            Name = "Kullanıcı Detay",
                            ParentId = 16,
                            Type = "Feature",
                            UpdatedAt = new DateTime(2026, 6, 4, 16, 15, 18, 249, DateTimeKind.Local).AddTicks(7200)
                        },
                        new
                        {
                            Id = 22,
                            Action = "Detail",
                            Address = "/User/Detail",
                            Controller = "User",
                            CreatedAt = new DateTime(2026, 6, 4, 16, 15, 18, 249, DateTimeKind.Local).AddTicks(7202),
                            Icon = "",
                            Menu = 0,
                            Name = "User Detail",
                            ParentId = 16,
                            Type = "Feature",
                            UpdatedAt = new DateTime(2026, 6, 4, 16, 15, 18, 249, DateTimeKind.Local).AddTicks(7202)
                        },
                        new
                        {
                            Id = 23,
                            Action = "GetUsers",
                            Address = "/User/GetUsers",
                            Controller = "User",
                            CreatedAt = new DateTime(2026, 6, 4, 16, 15, 18, 249, DateTimeKind.Local).AddTicks(7203),
                            Icon = "",
                            Menu = 0,
                            Name = "User GetUsers",
                            ParentId = 16,
                            Type = "Feature",
                            UpdatedAt = new DateTime(2026, 6, 4, 16, 15, 18, 249, DateTimeKind.Local).AddTicks(7204)
                        },
                        new
                        {
                            Id = 24,
                            Action = "GetUserById",
                            Address = "/User/GetUserById",
                            Controller = "User",
                            CreatedAt = new DateTime(2026, 6, 4, 16, 15, 18, 249, DateTimeKind.Local).AddTicks(7205),
                            Icon = "",
                            Menu = 0,
                            Name = "User GetById",
                            ParentId = 16,
                            Type = "Feature",
                            UpdatedAt = new DateTime(2026, 6, 4, 16, 15, 18, 249, DateTimeKind.Local).AddTicks(7206)
                        },
                        new
                        {
                            Id = 25,
                            Action = "CreateUser",
                            Address = "/User/CreateUser",
                            Controller = "User",
                            CreatedAt = new DateTime(2026, 6, 4, 16, 15, 18, 249, DateTimeKind.Local).AddTicks(7207),
                            Icon = "",
                            Menu = 0,
                            Name = "User CreateUser",
                            ParentId = 16,
                            Type = "Feature",
                            UpdatedAt = new DateTime(2026, 6, 4, 16, 15, 18, 249, DateTimeKind.Local).AddTicks(7207)
                        },
                        new
                        {
                            Id = 26,
                            Action = "UpdateUser",
                            Address = "/User/UpdateUser",
                            Controller = "User",
                            CreatedAt = new DateTime(2026, 6, 4, 16, 15, 18, 249, DateTimeKind.Local).AddTicks(7208),
                            Icon = "",
                            Menu = 0,
                            Name = "User UpdateUser",
                            ParentId = 16,
                            Type = "Feature",
                            UpdatedAt = new DateTime(2026, 6, 4, 16, 15, 18, 249, DateTimeKind.Local).AddTicks(7209)
                        },
                        new
                        {
                            Id = 27,
                            Action = "DeleteUser",
                            Address = "/User/DeleteUser",
                            Controller = "User",
                            CreatedAt = new DateTime(2026, 6, 4, 16, 15, 18, 249, DateTimeKind.Local).AddTicks(7210),
                            Icon = "",
                            Menu = 0,
                            Name = "User DeleteUser",
                            ParentId = 16,
                            Type = "Feature",
                            UpdatedAt = new DateTime(2026, 6, 4, 16, 15, 18, 249, DateTimeKind.Local).AddTicks(7211)
                        },
                        new
                        {
                            Id = 28,
                            Action = "ResetPassword",
                            Address = "/User/ResetPassword",
                            Controller = "User",
                            CreatedAt = new DateTime(2026, 6, 4, 16, 15, 18, 249, DateTimeKind.Local).AddTicks(7212),
                            Icon = "",
                            Menu = 0,
                            Name = "User ResetPassword",
                            ParentId = 16,
                            Type = "Feature",
                            UpdatedAt = new DateTime(2026, 6, 4, 16, 15, 18, 249, DateTimeKind.Local).AddTicks(7212)
                        });
                });

            modelBuilder.Entity("Entity.ModuleRoles", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("ModuleId")
                        .HasColumnType("integer");

                    b.Property<int>("RolId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ModuleId");

                    b.HasIndex("RolId");

                    b.HasIndex("UserId");

                    b.ToTable("ModuleRoles");

                    b.HasData(
                        new
                        {
                            Id = 21,
                            CreatedAt = new DateTime(2026, 6, 4, 16, 15, 18, 249, DateTimeKind.Local).AddTicks(7230),
                            ModuleId = 21,
                            RolId = 1,
                            UpdatedAt = new DateTime(2026, 6, 4, 16, 15, 18, 249, DateTimeKind.Local).AddTicks(7230),
                            UserId = 1
                        },
                        new
                        {
                            Id = 22,
                            CreatedAt = new DateTime(2026, 6, 4, 16, 15, 18, 249, DateTimeKind.Local).AddTicks(7231),
                            ModuleId = 22,
                            RolId = 1,
                            UpdatedAt = new DateTime(2026, 6, 4, 16, 15, 18, 249, DateTimeKind.Local).AddTicks(7232),
                            UserId = 1
                        },
                        new
                        {
                            Id = 23,
                            CreatedAt = new DateTime(2026, 6, 4, 16, 15, 18, 249, DateTimeKind.Local).AddTicks(7232),
                            ModuleId = 23,
                            RolId = 1,
                            UpdatedAt = new DateTime(2026, 6, 4, 16, 15, 18, 249, DateTimeKind.Local).AddTicks(7233),
                            UserId = 1
                        },
                        new
                        {
                            Id = 24,
                            CreatedAt = new DateTime(2026, 6, 4, 16, 15, 18, 249, DateTimeKind.Local).AddTicks(7234),
                            ModuleId = 24,
                            RolId = 1,
                            UpdatedAt = new DateTime(2026, 6, 4, 16, 15, 18, 249, DateTimeKind.Local).AddTicks(7234),
                            UserId = 1
                        },
                        new
                        {
                            Id = 25,
                            CreatedAt = new DateTime(2026, 6, 4, 16, 15, 18, 249, DateTimeKind.Local).AddTicks(7235),
                            ModuleId = 25,
                            RolId = 1,
                            UpdatedAt = new DateTime(2026, 6, 4, 16, 15, 18, 249, DateTimeKind.Local).AddTicks(7235),
                            UserId = 1
                        },
                        new
                        {
                            Id = 26,
                            CreatedAt = new DateTime(2026, 6, 4, 16, 15, 18, 249, DateTimeKind.Local).AddTicks(7236),
                            ModuleId = 26,
                            RolId = 1,
                            UpdatedAt = new DateTime(2026, 6, 4, 16, 15, 18, 249, DateTimeKind.Local).AddTicks(7236),
                            UserId = 1
                        },
                        new
                        {
                            Id = 27,
                            CreatedAt = new DateTime(2026, 6, 4, 16, 15, 18, 249, DateTimeKind.Local).AddTicks(7237),
                            ModuleId = 27,
                            RolId = 1,
                            UpdatedAt = new DateTime(2026, 6, 4, 16, 15, 18, 249, DateTimeKind.Local).AddTicks(7238),
                            UserId = 1
                        },
                        new
                        {
                            Id = 28,
                            CreatedAt = new DateTime(2026, 6, 4, 16, 15, 18, 249, DateTimeKind.Local).AddTicks(7238),
                            ModuleId = 28,
                            RolId = 1,
                            UpdatedAt = new DateTime(2026, 6, 4, 16, 15, 18, 249, DateTimeKind.Local).AddTicks(7239),
                            UserId = 1
                        });
                });

            modelBuilder.Entity("Entity.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Message")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("Entity.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 6, 4, 16, 15, 18, 249, DateTimeKind.Local).AddTicks(6352),
                            Name = "Süper Admin",
                            UpdatedAt = new DateTime(2026, 6, 4, 16, 15, 18, 249, DateTimeKind.Local).AddTicks(6362)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 6, 4, 16, 15, 18, 249, DateTimeKind.Local).AddTicks(6364),
                            Name = "Kullanıcı",
                            UpdatedAt = new DateTime(2026, 6, 4, 16, 15, 18, 249, DateTimeKind.Local).AddTicks(6364)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 6, 4, 16, 15, 18, 249, DateTimeKind.Local).AddTicks(6365),
                            Name = "Demo",
                            UpdatedAt = new DateTime(2026, 6, 4, 16, 15, 18, 249, DateTimeKind.Local).AddTicks(6366)
                        });
                });

            modelBuilder.Entity("Entity.Soru", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<List<Dictionary<string, string>>>("Cevaplar")
                        .HasColumnType("jsonb");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Dictionary<string, string>>("DogruCevap")
                        .HasColumnType("jsonb");

                    b.Property<string>("Hedef")
                        .HasColumnType("text");

                    b.Property<string>("OlcekMaddesi")
                        .HasColumnType("text");

                    b.Property<string>("SoruMetni")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("VideoPath")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Sorus");
                });

            modelBuilder.Entity("Entity.SoruUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("Puan")
                        .HasColumnType("integer");

                    b.Property<int>("SoruId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<string>("VerilenCevap")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("SoruId");

                    b.HasIndex("UserId");

                    b.ToTable("SoruUsers");
                });

            modelBuilder.Entity("Entity.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("CozumlemeTamamlandiMi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("DeviceToken")
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .HasColumnType("text");

                    b.Property<bool>("IlkGiris")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<bool>("KvkkApproved")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("OgrenciNo")
                        .HasColumnType("text");

                    b.Property<bool>("OnamApproved")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<byte[]>("PasswordHash")
                        .HasColumnType("bytea");

                    b.Property<byte[]>("PasswordSalt")
                        .HasColumnType("bytea");

                    b.Property<string>("Phone")
                        .HasColumnType("text");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.Property<bool>("SimulasyonTamamlandiMi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Surname")
                        .HasColumnType("text");

                    b.Property<int?>("ToplamPuan")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("UserName")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CozumlemeTamamlandiMi = false,
                            IlkGiris = false,
                            KvkkApproved = false,
                            OnamApproved = false,
                            PasswordHash = new byte[] { 81, 242, 69, 158, 245, 48, 179, 239, 24, 65, 37, 17, 119, 102, 34, 103, 248, 10, 31, 225, 148, 147, 32, 149, 235, 20, 172, 1, 127, 9, 48, 212, 219, 173, 162, 67, 179, 210, 198, 155, 230, 242, 106, 88, 209, 185, 119, 34, 5, 44, 202, 211, 177, 217, 158, 61, 180, 185, 106, 188, 31, 144, 2, 50 },
                            PasswordSalt = new byte[] { 115, 150, 60, 162, 20, 173, 36, 117, 31, 201, 163, 222, 228, 41, 140, 34, 68, 104, 157, 14, 177, 219, 225, 99, 22, 89, 188, 9, 56, 42, 25, 65, 42, 200, 201, 42, 59, 1, 186, 56, 245, 144, 41, 221, 122, 96, 179, 155, 245, 191, 115, 106, 171, 242, 194, 16, 27, 17, 140, 205, 180, 14, 72, 100, 68, 244, 193, 139, 206, 197, 81, 106, 242, 151, 23, 54, 67, 25, 109, 7, 153, 152, 201, 27, 58, 219, 14, 4, 75, 94, 196, 235, 159, 232, 229, 30, 25, 189, 14, 229, 183, 251, 27, 161, 87, 252, 52, 242, 146, 242, 204, 213, 220, 209, 179, 244, 145, 254, 151, 45, 25, 65, 166, 113, 48, 10, 245, 200 },
                            Phone = "00000000000",
                            RoleId = 1,
                            SimulasyonTamamlandiMi = false
                        });
                });

            modelBuilder.Entity("Entity.CozumlemeSoruUser", b =>
                {
                    b.HasOne("Entity.User", "User")
                        .WithMany("CozumlemeSoruUsers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Entity.ModuleRoles", b =>
                {
                    b.HasOne("Entity.Module", "Module")
                        .WithMany("ModuleRoles")
                        .HasForeignKey("ModuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entity.Role", "Role")
                        .WithMany("ModuleRoles")
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entity.User", "User")
                        .WithMany("ModuleRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Module");

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Entity.SoruUser", b =>
                {
                    b.HasOne("Entity.Soru", "Soru")
                        .WithMany("SoruUsers")
                        .HasForeignKey("SoruId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entity.User", "User")
                        .WithMany("SoruUsers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Soru");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Entity.User", b =>
                {
                    b.HasOne("Entity.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Entity.Module", b =>
                {
                    b.Navigation("ModuleRoles");
                });

            modelBuilder.Entity("Entity.Role", b =>
                {
                    b.Navigation("ModuleRoles");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("Entity.Soru", b =>
                {
                    b.Navigation("SoruUsers");
                });

            modelBuilder.Entity("Entity.User", b =>
                {
                    b.Navigation("CozumlemeSoruUsers");

                    b.Navigation("ModuleRoles");

                    b.Navigation("SoruUsers");
                });
#pragma warning restore 612, 618
        }
    }
}
