// <auto-generated />
using System;
using System.Collections.Generic;
using DataAccessLayer.EntityFramework.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DataAccessLayer.Migrations
{
    [DbContext(typeof(BaseDbContext))]
    [Migration("20260616123632_soru_transcript_added")]
    partial class soru_transcript_added
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Entity.CozumlemeSoruUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Asama")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<List<Dictionary<string, string>>>("SoruCevap")
                        .HasColumnType("jsonb");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("CozumlemeSoruUsers");
                });

            modelBuilder.Entity("Entity.Module", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .HasColumnType("text");

                    b.Property<string>("Address")
                        .HasColumnType("text");

                    b.Property<string>("Controller")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Icon")
                        .HasColumnType("text");

                    b.Property<int>("Menu")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<int>("ParentId")
                        .HasColumnType("integer");

                    b.Property<string>("Type")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.ToTable("Modules");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Action = "Index",
                            Address = "/Home/Index",
                            Controller = "Home",
                            CreatedAt = new DateTime(2026, 6, 16, 15, 36, 32, 263, DateTimeKind.Local).AddTicks(2957),
                            Icon = "fas fa-home",
                            Menu = 1,
                            Name = "Ana Sayfa",
                            ParentId = 0,
                            Type = "Page",
                            UpdatedAt = new DateTime(2026, 6, 16, 15, 36, 32, 263, DateTimeKind.Local).AddTicks(2959)
                        },
                        new
                        {
                            Id = 2,
                            Action = "Index",
                            Address = "Index",
                            Controller = "Role",
                            CreatedAt = new DateTime(2026, 6, 16, 15, 36, 32, 263, DateTimeKind.Local).AddTicks(2960),
                            Icon = "icon-user-lock",
                            Menu = 1,
                            Name = "Rol Yönetimi",
                            ParentId = 0,
                            Type = "Category",
                            UpdatedAt = new DateTime(2026, 6, 16, 15, 36, 32, 263, DateTimeKind.Local).AddTicks(2961)
                        },
                        new
                        {
                            Id = 3,
                            Action = "Create",
                            Address = "/Role/Create",
                            Controller = "Role",
                            CreatedAt = new DateTime(2026, 6, 16, 15, 36, 32, 263, DateTimeKind.Local).AddTicks(2963),
                            Icon = "",
                            Menu = 1,
                            Name = "Rol Ekle",
                            ParentId = 2,
                            Type = "Page",
                            UpdatedAt = new DateTime(2026, 6, 16, 15, 36, 32, 263, DateTimeKind.Local).AddTicks(2964)
                        },
                        new
                        {
                            Id = 4,
                            Action = "Edit",
                            Address = "/Role/Edit",
                            Controller = "Role",
                            CreatedAt = new DateTime(2026, 6, 16, 15, 36, 32, 263, DateTimeKind.Local).AddTicks(2965),
                            Icon = "",
                            Menu = 0,
                            Name = "Rol Düzenleme",
                            ParentId = 2,
                            Type = "Feature",
                            UpdatedAt = new DateTime(2026, 6, 16, 15, 36, 32, 263, DateTimeKind.Local).AddTicks(2965)
                        },
                        new
                        {
                            Id = 5,
                            Action = "Delete",
                            Address = "/Role/Delete",
                            Controller = "Role",
                            CreatedAt = new DateTime(2026, 6, 16, 15, 36, 32, 263, DateTimeKind.Local).AddTicks(2966),
                            Icon = "",
                            Menu = 0,
                            Name = "Rol Silme",
                            ParentId = 2,
                            Type = "Feature",
                            UpdatedAt = new DateTime(2026, 6, 16, 15, 36, 32, 263, DateTimeKind.Local).AddTicks(2967)
                        },
                        new
                        {
                            Id = 6,
                            Action = "GetById",
                            Address = "/Role/GetById",
                            Controller = "Role",
                            CreatedAt = new DateTime(2026, 6, 16, 15, 36, 32, 263, DateTimeKind.Local).AddTicks(2968),
                            Icon = "",
                            Menu = 0,
                            Name = "Id Bazlı Rol Getirme",
                            ParentId = 2,
                            Type = "Feature",
                            UpdatedAt = new DateTime(2026, 6, 16, 15, 36, 32, 263, DateTimeKind.Local).AddTicks(2968)
                        },
                        new
                        {
                            Id = 7,
                            Action = "/Role/Index",
                            Address = "/Role/Index",
                            Controller = "Role",
                            CreatedAt = new DateTime(2026, 6, 16, 15, 36, 32, 263, DateTimeKind.Local).AddTicks(2969),
                            Icon = "",
                            Menu = 1,
                            Name = "Rol Listesi",
                            ParentId = 2,
                            Type = "Page",
                            UpdatedAt = new DateTime(2026, 6, 16, 15, 36, 32, 263, DateTimeKind.Local).AddTicks(2970)
                        },
                        new
                        {
                            Id = 8,
                            Action = "GetList",
                            Address = "/Role/GetList",
                            Controller = "Role",
                            CreatedAt = new DateTime(2026, 6, 16, 15, 36, 32, 263, DateTimeKind.Local).AddTicks(2971),
                            Icon = "",
                            Menu = 0,
                            Name = "Rol Listesi",
                            ParentId = 2,
                            Type = "Page",
                            UpdatedAt = new DateTime(2026, 6, 16, 15, 36, 32, 263, DateTimeKind.Local).AddTicks(2971)
                        },
                        new
                        {
                            Id = 9,
                            Action = "Authentication",
                            Address = "/Role/Authentication",
                            Controller = "Role",
                            CreatedAt = new DateTime(2026, 6, 16, 15, 36, 32, 263, DateTimeKind.Local).AddTicks(2972),
                            Icon = "",
                            Menu = 0,
                            Name = "Rol Yetkilendirme",
                            ParentId = 2,
                            Type = "Page",
                            UpdatedAt = new DateTime(2026, 6, 16, 15, 36, 32, 263, DateTimeKind.Local).AddTicks(2972)
                        },
                        new
                        {
                            Id = 10,
                            Action = "Index",
                            Address = "/Module/Index",
                            Controller = "Module",
                            CreatedAt = new DateTime(2026, 6, 16, 15, 36, 32, 263, DateTimeKind.Local).AddTicks(3072),
                            Icon = "fas fa-align-justify",
                            Menu = 1,
                            Name = "Modül Yönetimi",
                            ParentId = 0,
                            Type = "Category",
                            UpdatedAt = new DateTime(2026, 6, 16, 15, 36, 32, 263, DateTimeKind.Local).AddTicks(3072)
                        },
                        new
                        {
                            Id = 11,
                            Action = "/Module/Index",
                            Address = "/Module/Index",
                            Controller = "Module",
                            CreatedAt = new DateTime(2026, 6, 16, 15, 36, 32, 263, DateTimeKind.Local).AddTicks(3074),
                            Icon = "",
                            Menu = 1,
                            Name = "Modül Listesi",
                            ParentId = 10,
                            Type = "Page",
                            UpdatedAt = new DateTime(2026, 6, 16, 15, 36, 32, 263, DateTimeKind.Local).AddTicks(3074)
                        },
                        new
                        {
                            Id = 12,
                            Action = "GetList",
                            Address = "/Module/GetList",
                            Controller = "Module",
                            CreatedAt = new DateTime(2026, 6, 16, 15, 36, 32, 263, DateTimeKind.Local).AddTicks(3075),
                            Icon = "",
                            Menu = 0,
                            Name = "Modül Listesi",
                            ParentId = 10,
                            Type = "Feature",
                            UpdatedAt = new DateTime(2026, 6, 16, 15, 36, 32, 263, DateTimeKind.Local).AddTicks(3076)
                        },
                        new
                        {
                            Id = 13,
                            Action = "Delete",
                            Address = "/Module/Delete",
                            Controller = "Module",
                            CreatedAt = new DateTime(2026, 6, 16, 15, 36, 32, 263, DateTimeKind.Local).AddTicks(3078),
                            Icon = "",
                            Menu = 0,
                            Name = "Modül Silme",
                            ParentId = 10,
                            Type = "Feature",
                            UpdatedAt = new DateTime(2026, 6, 16, 15, 36, 32, 263, DateTimeKind.Local).AddTicks(3078)
                        },
                        new
                        {
                            Id = 14,
                            Action = "GetById",
                            Address = "/Module/GetById",
                            Controller = "Module",
                            CreatedAt = new DateTime(2026, 6, 16, 15, 36, 32, 263, DateTimeKind.Local).AddTicks(3079),
                            Icon = "",
                            Menu = 10,
                            Name = "Id Bazlı Rol Getirmea",
                            ParentId = 3,
                            Type = "Feature",
                            UpdatedAt = new DateTime(2026, 6, 16, 15, 36, 32, 263, DateTimeKind.Local).AddTicks(3080)
                        },
                        new
                        {
                            Id = 15,
                            Action = "/Module/Create",
                            Address = "/Module/Create",
                            Controller = "Module",
                            CreatedAt = new DateTime(2026, 6, 16, 15, 36, 32, 263, DateTimeKind.Local).AddTicks(3081),
                            Icon = "",
                            Menu = 1,
                            Name = "Modül Ekle",
                            ParentId = 10,
                            Type = "Page",
                            UpdatedAt = new DateTime(2026, 6, 16, 15, 36, 32, 263, DateTimeKind.Local).AddTicks(3081)
                        },
                        new
                        {
                            Id = 16,
                            Action = "Index",
                            Address = "/Mail/Index",
                            Controller = "Mail",
                            CreatedAt = new DateTime(2026, 6, 16, 15, 36, 32, 263, DateTimeKind.Local).AddTicks(3082),
                            Icon = "icon-mail5 mr-3",
                            Menu = 1,
                            Name = "E-Posta Yönetimi",
                            ParentId = 16,
                            Type = "Category",
                            UpdatedAt = new DateTime(2026, 6, 16, 15, 36, 32, 263, DateTimeKind.Local).AddTicks(3083)
                        },
                        new
                        {
                            Id = 17,
                            Action = "Index",
                            Address = "/Mail/Index",
                            Controller = "Mail",
                            CreatedAt = new DateTime(2026, 6, 16, 15, 36, 32, 263, DateTimeKind.Local).AddTicks(3084),
                            Icon = "",
                            Menu = 1,
                            Name = "E-Posta Listesi",
                            ParentId = 16,
                            Type = "Page",
                            UpdatedAt = new DateTime(2026, 6, 16, 15, 36, 32, 263, DateTimeKind.Local).AddTicks(3084)
                        },
                        new
                        {
                            Id = 18,
                            Action = "GetList",
                            Address = "/Mail/GetList",
                            Controller = "Mail",
                            CreatedAt = new DateTime(2026, 6, 16, 15, 36, 32, 263, DateTimeKind.Local).AddTicks(3086),
                            Icon = "",
                            Menu = 0,
                            Name = "E-Posta Listesi",
                            ParentId = 16,
                            Type = "Feature",
                            UpdatedAt = new DateTime(2026, 6, 16, 15, 36, 32, 263, DateTimeKind.Local).AddTicks(3086)
                        },
                        new
                        {
                            Id = 19,
                            Action = "/kullanici_islemleri",
                            Address = "/User/KullaniciIslemleri",
                            Controller = "User",
                            CreatedAt = new DateTime(2026, 6, 16, 15, 36, 32, 263, DateTimeKind.Local).AddTicks(3087),
                            Icon = "",
                            Menu = 0,
                            Name = "Kullanıcı İşlemleri",
                            ParentId = 16,
                            Type = "Feature",
                            UpdatedAt = new DateTime(2026, 6, 16, 15, 36, 32, 263, DateTimeKind.Local).AddTicks(3088)
                        },
                        new
                        {
                            Id = 20,
                            Action = "Api",
                            Address = "Api",
                            Controller = "Api",
                            CreatedAt = new DateTime(2026, 6, 16, 15, 36, 32, 263, DateTimeKind.Local).AddTicks(3089),
                            Icon = "",
                            Menu = 0,
                            Name = "Api Modules",
                            ParentId = 16,
                            Type = "Feature",
                            UpdatedAt = new DateTime(2026, 6, 16, 15, 36, 32, 263, DateTimeKind.Local).AddTicks(3089)
                        },
                        new
                        {
                            Id = 21,
                            Action = "/kullanici_detay",
                            Address = "/User/Detail",
                            Controller = "User",
                            CreatedAt = new DateTime(2026, 6, 16, 15, 36, 32, 263, DateTimeKind.Local).AddTicks(3090),
                            Icon = "",
                            Menu = 0,
                            Name = "Kullanıcı Detay",
                            ParentId = 16,
                            Type = "Feature",
                            UpdatedAt = new DateTime(2026, 6, 16, 15, 36, 32, 263, DateTimeKind.Local).AddTicks(3091)
                        },
                        new
                        {
                            Id = 22,
                            Action = "Detail",
                            Address = "/User/Detail",
                            Controller = "User",
                            CreatedAt = new DateTime(2026, 6, 16, 15, 36, 32, 263, DateTimeKind.Local).AddTicks(3092),
                            Icon = "",
                            Menu = 0,
                            Name = "User Detail",
                            ParentId = 16,
                            Type = "Feature",
                            UpdatedAt = new DateTime(2026, 6, 16, 15, 36, 32, 263, DateTimeKind.Local).AddTicks(3093)
                        },
                        new
                        {
                            Id = 23,
                            Action = "GetUsers",
                            Address = "/User/GetUsers",
                            Controller = "User",
                            CreatedAt = new DateTime(2026, 6, 16, 15, 36, 32, 263, DateTimeKind.Local).AddTicks(3094),
                            Icon = "",
                            Menu = 0,
                            Name = "User GetUsers",
                            ParentId = 16,
                            Type = "Feature",
                            UpdatedAt = new DateTime(2026, 6, 16, 15, 36, 32, 263, DateTimeKind.Local).AddTicks(3094)
                        },
                        new
                        {
                            Id = 24,
                            Action = "GetUserById",
                            Address = "/User/GetUserById",
                            Controller = "User",
                            CreatedAt = new DateTime(2026, 6, 16, 15, 36, 32, 263, DateTimeKind.Local).AddTicks(3096),
                            Icon = "",
                            Menu = 0,
                            Name = "User GetById",
                            ParentId = 16,
                            Type = "Feature",
                            UpdatedAt = new DateTime(2026, 6, 16, 15, 36, 32, 263, DateTimeKind.Local).AddTicks(3096)
                        },
                        new
                        {
                            Id = 25,
                            Action = "CreateUser",
                            Address = "/User/CreateUser",
                            Controller = "User",
                            CreatedAt = new DateTime(2026, 6, 16, 15, 36, 32, 263, DateTimeKind.Local).AddTicks(3097),
                            Icon = "",
                            Menu = 0,
                            Name = "User CreateUser",
                            ParentId = 16,
                            Type = "Feature",
                            UpdatedAt = new DateTime(2026, 6, 16, 15, 36, 32, 263, DateTimeKind.Local).AddTicks(3097)
                        },
                        new
                        {
                            Id = 26,
                            Action = "UpdateUser",
                            Address = "/User/UpdateUser",
                            Controller = "User",
                            CreatedAt = new DateTime(2026, 6, 16, 15, 36, 32, 263, DateTimeKind.Local).AddTicks(3098),
                            Icon = "",
                            Menu = 0,
                            Name = "User UpdateUser",
                            ParentId = 16,
                            Type = "Feature",
                            UpdatedAt = new DateTime(2026, 6, 16, 15, 36, 32, 263, DateTimeKind.Local).AddTicks(3099)
                        },
                        new
                        {
                            Id = 27,
                            Action = "DeleteUser",
                            Address = "/User/DeleteUser",
                            Controller = "User",
                            CreatedAt = new DateTime(2026, 6, 16, 15, 36, 32, 263, DateTimeKind.Local).AddTicks(3100),
                            Icon = "",
                            Menu = 0,
                            Name = "User DeleteUser",
                            ParentId = 16,
                            Type = "Feature",
                            UpdatedAt = new DateTime(2026, 6, 16, 15, 36, 32, 263, DateTimeKind.Local).AddTicks(3100)
                        },
                        new
                        {
                            Id = 28,
                            Action = "ResetPassword",
                            Address = "/User/ResetPassword",
                            Controller = "User",
                            CreatedAt = new DateTime(2026, 6, 16, 15, 36, 32, 263, DateTimeKind.Local).AddTicks(3101),
                            Icon = "",
                            Menu = 0,
                            Name = "User ResetPassword",
                            ParentId = 16,
                            Type = "Feature",
                            UpdatedAt = new DateTime(2026, 6, 16, 15, 36, 32, 263, DateTimeKind.Local).AddTicks(3102)
                        });
                });

            modelBuilder.Entity("Entity.ModuleRoles", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("ModuleId")
                        .HasColumnType("integer");

                    b.Property<int>("RolId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ModuleId");

                    b.HasIndex("RolId");

                    b.HasIndex("UserId");

                    b.ToTable("ModuleRoles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 6, 16, 15, 36, 32, 263, DateTimeKind.Local).AddTicks(3132),
                            ModuleId = 1,
                            RolId = 1,
                            UpdatedAt = new DateTime(2026, 6, 16, 15, 36, 32, 263, DateTimeKind.Local).AddTicks(3133),
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 6, 16, 15, 36, 32, 263, DateTimeKind.Local).AddTicks(3134),
                            ModuleId = 2,
                            RolId = 1,
                            UpdatedAt = new DateTime(2026, 6, 16, 15, 36, 32, 263, DateTimeKind.Local).AddTicks(3134),
                            UserId = 1
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 6, 16, 15, 36, 32, 263, DateTimeKind.Local).AddTicks(3135),
                            ModuleId = 3,
                            RolId = 1,
                            UpdatedAt = new DateTime(2026, 6, 16, 15, 36, 32, 263, DateTimeKind.Local).AddTicks(3136),
                            UserId = 1
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 6, 16, 15, 36, 32, 263, DateTimeKind.Local).AddTicks(3136),
                            ModuleId = 4,
                            RolId = 1,
                            UpdatedAt = new DateTime(2026, 6, 16, 15, 36, 32, 263, DateTimeKind.Local).AddTicks(3137),
                            UserId = 1
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2026, 6, 16, 15, 36, 32, 263, DateTimeKind.Local).AddTicks(3140),
                            ModuleId = 5,
                            RolId = 1,
                            UpdatedAt = new DateTime(2026, 6, 16, 15, 36, 32, 263, DateTimeKind.Local).AddTicks(3140),
                            UserId = 1
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2026, 6, 16, 15, 36, 32, 263, DateTimeKind.Local).AddTicks(3141),
                            ModuleId = 6,
                            RolId = 1,
                            UpdatedAt = new DateTime(2026, 6, 16, 15, 36, 32, 263, DateTimeKind.Local).AddTicks(3141),
                            UserId = 1
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2026, 6, 16, 15, 36, 32, 263, DateTimeKind.Local).AddTicks(3142),
                            ModuleId = 7,
                            RolId = 1,
                            UpdatedAt = new DateTime(2026, 6, 16, 15, 36, 32, 263, DateTimeKind.Local).AddTicks(3143),
                            UserId = 1
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2026, 6, 16, 15, 36, 32, 263, DateTimeKind.Local).AddTicks(3143),
                            ModuleId = 8,
                            RolId = 1,
                            UpdatedAt = new DateTime(2026, 6, 16, 15, 36, 32, 263, DateTimeKind.Local).AddTicks(3144),
                            UserId = 1
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2026, 6, 16, 15, 36, 32, 263, DateTimeKind.Local).AddTicks(3144),
                            ModuleId = 9,
                            RolId = 1,
                            UpdatedAt = new DateTime(2026, 6, 16, 15, 36, 32, 263, DateTimeKind.Local).AddTicks(3145),
                            UserId = 1
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2026, 6, 16, 15, 36, 32, 263, DateTimeKind.Local).AddTicks(3146),
                            ModuleId = 10,
                            RolId = 1,
                            UpdatedAt = new DateTime(2026, 6, 16, 15, 36, 32, 263, DateTimeKind.Local).AddTicks(3146),
                            UserId = 1
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2026, 6, 16, 15, 36, 32, 263, DateTimeKind.Local).AddTicks(3147),
                            ModuleId = 11,
                            RolId = 1,
                            UpdatedAt = new DateTime(2026, 6, 16, 15, 36, 32, 263, DateTimeKind.Local).AddTicks(3147),
                            UserId = 1
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2026, 6, 16, 15, 36, 32, 263, DateTimeKind.Local).AddTicks(3148),
                            ModuleId = 12,
                            RolId = 1,
                            UpdatedAt = new DateTime(2026, 6, 16, 15, 36, 32, 263, DateTimeKind.Local).AddTicks(3148),
                            UserId = 1
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(2026, 6, 16, 15, 36, 32, 263, DateTimeKind.Local).AddTicks(3149),
                            ModuleId = 13,
                            RolId = 1,
                            UpdatedAt = new DateTime(2026, 6, 16, 15, 36, 32, 263, DateTimeKind.Local).AddTicks(3150),
                            UserId = 1
                        },
                        new
                        {
                            Id = 14,
                            CreatedAt = new DateTime(2026, 6, 16, 15, 36, 32, 263, DateTimeKind.Local).AddTicks(3150),
                            ModuleId = 14,
                            RolId = 1,
                            UpdatedAt = new DateTime(2026, 6, 16, 15, 36, 32, 263, DateTimeKind.Local).AddTicks(3151),
                            UserId = 1
                        },
                        new
                        {
                            Id = 15,
                            CreatedAt = new DateTime(2026, 6, 16, 15, 36, 32, 263, DateTimeKind.Local).AddTicks(3152),
                            ModuleId = 15,
                            RolId = 1,
                            UpdatedAt = new DateTime(2026, 6, 16, 15, 36, 32, 263, DateTimeKind.Local).AddTicks(3153),
                            UserId = 1
                        },
                        new
                        {
                            Id = 16,
                            CreatedAt = new DateTime(2026, 6, 16, 15, 36, 32, 263, DateTimeKind.Local).AddTicks(3153),
                            ModuleId = 16,
                            RolId = 1,
                            UpdatedAt = new DateTime(2026, 6, 16, 15, 36, 32, 263, DateTimeKind.Local).AddTicks(3154),
                            UserId = 1
                        },
                        new
                        {
                            Id = 17,
                            CreatedAt = new DateTime(2026, 6, 16, 15, 36, 32, 263, DateTimeKind.Local).AddTicks(3155),
                            ModuleId = 17,
                            RolId = 1,
                            UpdatedAt = new DateTime(2026, 6, 16, 15, 36, 32, 263, DateTimeKind.Local).AddTicks(3155),
                            UserId = 1
                        },
                        new
                        {
                            Id = 18,
                            CreatedAt = new DateTime(2026, 6, 16, 15, 36, 32, 263, DateTimeKind.Local).AddTicks(3156),
                            ModuleId = 18,
                            RolId = 1,
                            UpdatedAt = new DateTime(2026, 6, 16, 15, 36, 32, 263, DateTimeKind.Local).AddTicks(3156),
                            UserId = 1
                        },
                        new
                        {
                            Id = 19,
                            CreatedAt = new DateTime(2026, 6, 16, 15, 36, 32, 263, DateTimeKind.Local).AddTicks(3157),
                            ModuleId = 19,
                            RolId = 1,
                            UpdatedAt = new DateTime(2026, 6, 16, 15, 36, 32, 263, DateTimeKind.Local).AddTicks(3157),
                            UserId = 1
                        },
                        new
                        {
                            Id = 20,
                            CreatedAt = new DateTime(2026, 6, 16, 15, 36, 32, 263, DateTimeKind.Local).AddTicks(3158),
                            ModuleId = 20,
                            RolId = 1,
                            UpdatedAt = new DateTime(2026, 6, 16, 15, 36, 32, 263, DateTimeKind.Local).AddTicks(3159),
                            UserId = 1
                        },
                        new
                        {
                            Id = 21,
                            CreatedAt = new DateTime(2026, 6, 16, 15, 36, 32, 263, DateTimeKind.Local).AddTicks(3159),
                            ModuleId = 21,
                            RolId = 1,
                            UpdatedAt = new DateTime(2026, 6, 16, 15, 36, 32, 263, DateTimeKind.Local).AddTicks(3160),
                            UserId = 1
                        },
                        new
                        {
                            Id = 22,
                            CreatedAt = new DateTime(2026, 6, 16, 15, 36, 32, 263, DateTimeKind.Local).AddTicks(3161),
                            ModuleId = 22,
                            RolId = 1,
                            UpdatedAt = new DateTime(2026, 6, 16, 15, 36, 32, 263, DateTimeKind.Local).AddTicks(3161),
                            UserId = 1
                        },
                        new
                        {
                            Id = 23,
                            CreatedAt = new DateTime(2026, 6, 16, 15, 36, 32, 263, DateTimeKind.Local).AddTicks(3162),
                            ModuleId = 23,
                            RolId = 1,
                            UpdatedAt = new DateTime(2026, 6, 16, 15, 36, 32, 263, DateTimeKind.Local).AddTicks(3162),
                            UserId = 1
                        },
                        new
                        {
                            Id = 24,
                            CreatedAt = new DateTime(2026, 6, 16, 15, 36, 32, 263, DateTimeKind.Local).AddTicks(3163),
                            ModuleId = 24,
                            RolId = 1,
                            UpdatedAt = new DateTime(2026, 6, 16, 15, 36, 32, 263, DateTimeKind.Local).AddTicks(3163),
                            UserId = 1
                        },
                        new
                        {
                            Id = 25,
                            CreatedAt = new DateTime(2026, 6, 16, 15, 36, 32, 263, DateTimeKind.Local).AddTicks(3164),
                            ModuleId = 25,
                            RolId = 1,
                            UpdatedAt = new DateTime(2026, 6, 16, 15, 36, 32, 263, DateTimeKind.Local).AddTicks(3164),
                            UserId = 1
                        },
                        new
                        {
                            Id = 26,
                            CreatedAt = new DateTime(2026, 6, 16, 15, 36, 32, 263, DateTimeKind.Local).AddTicks(3165),
                            ModuleId = 26,
                            RolId = 1,
                            UpdatedAt = new DateTime(2026, 6, 16, 15, 36, 32, 263, DateTimeKind.Local).AddTicks(3166),
                            UserId = 1
                        },
                        new
                        {
                            Id = 27,
                            CreatedAt = new DateTime(2026, 6, 16, 15, 36, 32, 263, DateTimeKind.Local).AddTicks(3166),
                            ModuleId = 27,
                            RolId = 1,
                            UpdatedAt = new DateTime(2026, 6, 16, 15, 36, 32, 263, DateTimeKind.Local).AddTicks(3167),
                            UserId = 1
                        },
                        new
                        {
                            Id = 28,
                            CreatedAt = new DateTime(2026, 6, 16, 15, 36, 32, 263, DateTimeKind.Local).AddTicks(3168),
                            ModuleId = 28,
                            RolId = 1,
                            UpdatedAt = new DateTime(2026, 6, 16, 15, 36, 32, 263, DateTimeKind.Local).AddTicks(3168),
                            UserId = 1
                        });
                });

            modelBuilder.Entity("Entity.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Message")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("Entity.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 6, 16, 15, 36, 32, 263, DateTimeKind.Local).AddTicks(2094),
                            Name = "Süper Admin",
                            UpdatedAt = new DateTime(2026, 6, 16, 15, 36, 32, 263, DateTimeKind.Local).AddTicks(2108)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 6, 16, 15, 36, 32, 263, DateTimeKind.Local).AddTicks(2109),
                            Name = "Kullanıcı",
                            UpdatedAt = new DateTime(2026, 6, 16, 15, 36, 32, 263, DateTimeKind.Local).AddTicks(2110)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 6, 16, 15, 36, 32, 263, DateTimeKind.Local).AddTicks(2111),
                            Name = "Demo",
                            UpdatedAt = new DateTime(2026, 6, 16, 15, 36, 32, 263, DateTimeKind.Local).AddTicks(2111)
                        });
                });

            modelBuilder.Entity("Entity.Soru", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<List<Dictionary<string, string>>>("Cevaplar")
                        .HasColumnType("jsonb");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Dictionary<string, string>>("DogruCevap")
                        .HasColumnType("jsonb");

                    b.Property<string>("Hedef")
                        .HasColumnType("text");

                    b.Property<string>("OlcekMaddesi")
                        .HasColumnType("text");

                    b.Property<string>("SoruMetni")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("VideoPath")
                        .HasColumnType("text");

                    b.Property<string>("VideoTranscript")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Sorus");
                });

            modelBuilder.Entity("Entity.SoruUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("Puan")
                        .HasColumnType("integer");

                    b.Property<int>("SoruId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<string>("VerilenCevap")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("SoruId");

                    b.HasIndex("UserId");

                    b.ToTable("SoruUsers");
                });

            modelBuilder.Entity("Entity.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("CozumlemeTamamlandiMi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("DeviceToken")
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .HasColumnType("text");

                    b.Property<bool>("IlkGiris")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<bool>("KvkkApproved")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("OgrenciNo")
                        .HasColumnType("text");

                    b.Property<bool>("OnamApproved")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<byte[]>("PasswordHash")
                        .HasColumnType("bytea");

                    b.Property<byte[]>("PasswordSalt")
                        .HasColumnType("bytea");

                    b.Property<string>("Phone")
                        .HasColumnType("text");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.Property<bool>("SimulasyonTamamlandiMi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Surname")
                        .HasColumnType("text");

                    b.Property<int?>("ToplamPuan")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("UserName")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CozumlemeTamamlandiMi = false,
                            IlkGiris = false,
                            KvkkApproved = false,
                            OnamApproved = false,
                            PasswordHash = new byte[] { 108, 248, 228, 138, 107, 229, 30, 166, 18, 217, 16, 112, 5, 208, 235, 46, 68, 115, 53, 105, 231, 243, 90, 84, 226, 100, 245, 78, 133, 125, 91, 101, 235, 112, 40, 1, 175, 168, 91, 88, 236, 157, 123, 23, 48, 158, 127, 100, 100, 202, 231, 20, 12, 8, 169, 3, 92, 135, 48, 104, 228, 111, 232, 172 },
                            PasswordSalt = new byte[] { 146, 84, 180, 242, 4, 119, 254, 250, 184, 184, 80, 176, 94, 44, 10, 94, 196, 77, 43, 160, 28, 37, 251, 215, 207, 245, 84, 43, 152, 98, 71, 225, 173, 89, 65, 42, 109, 197, 71, 252, 175, 30, 108, 139, 157, 40, 192, 156, 81, 63, 22, 159, 18, 176, 42, 121, 47, 227, 115, 194, 103, 55, 170, 116, 229, 130, 114, 242, 161, 57, 143, 210, 29, 210, 44, 74, 165, 186, 111, 54, 238, 195, 181, 141, 51, 88, 153, 118, 252, 37, 0, 96, 133, 93, 66, 149, 191, 175, 231, 250, 13, 227, 230, 232, 125, 159, 10, 90, 146, 101, 120, 195, 25, 240, 186, 251, 1, 243, 204, 6, 149, 177, 129, 174, 68, 31, 69, 3 },
                            Phone = "00000000000",
                            RoleId = 1,
                            SimulasyonTamamlandiMi = false
                        });
                });

            modelBuilder.Entity("Entity.CozumlemeSoruUser", b =>
                {
                    b.HasOne("Entity.User", "User")
                        .WithMany("CozumlemeSoruUsers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Entity.ModuleRoles", b =>
                {
                    b.HasOne("Entity.Module", "Module")
                        .WithMany("ModuleRoles")
                        .HasForeignKey("ModuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entity.Role", "Role")
                        .WithMany("ModuleRoles")
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entity.User", "User")
                        .WithMany("ModuleRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Module");

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Entity.SoruUser", b =>
                {
                    b.HasOne("Entity.Soru", "Soru")
                        .WithMany("SoruUsers")
                        .HasForeignKey("SoruId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entity.User", "User")
                        .WithMany("SoruUsers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Soru");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Entity.User", b =>
                {
                    b.HasOne("Entity.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Entity.Module", b =>
                {
                    b.Navigation("ModuleRoles");
                });

            modelBuilder.Entity("Entity.Role", b =>
                {
                    b.Navigation("ModuleRoles");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("Entity.Soru", b =>
                {
                    b.Navigation("SoruUsers");
                });

            modelBuilder.Entity("Entity.User", b =>
                {
                    b.Navigation("CozumlemeSoruUsers");

                    b.Navigation("ModuleRoles");

                    b.Navigation("SoruUsers");
                });
#pragma warning restore 612, 618
        }
    }
}
