// <auto-generated />
using System;
using DataAccessLayer.EntityFramework.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DataAccessLayer.Migrations
{
    [DbContext(typeof(BaseDbContext))]
    [Migration("20260604062543_first_mig")]
    partial class first_mig
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Entity.Module", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .HasColumnType("text");

                    b.Property<string>("Address")
                        .HasColumnType("text");

                    b.Property<string>("Controller")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Icon")
                        .HasColumnType("text");

                    b.Property<int>("Menu")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<int>("ParentId")
                        .HasColumnType("integer");

                    b.Property<string>("Type")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.ToTable("Modules");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Action = "Index",
                            Address = "/Home/Index",
                            Controller = "Home",
                            CreatedAt = new DateTime(2026, 6, 4, 9, 25, 43, 644, DateTimeKind.Local).AddTicks(89),
                            Icon = "fas fa-home",
                            Menu = 1,
                            Name = "Ana Sayfa",
                            ParentId = 0,
                            Type = "Page",
                            UpdatedAt = new DateTime(2026, 6, 4, 9, 25, 43, 644, DateTimeKind.Local).AddTicks(93)
                        },
                        new
                        {
                            Id = 2,
                            Action = "Index",
                            Address = "/Role/Index",
                            Controller = "Role",
                            CreatedAt = new DateTime(2026, 6, 4, 9, 25, 43, 644, DateTimeKind.Local).AddTicks(96),
                            Icon = "icon-user-lock",
                            Menu = 1,
                            Name = "Rol Yönetimi",
                            ParentId = 0,
                            Type = "Category",
                            UpdatedAt = new DateTime(2026, 6, 4, 9, 25, 43, 644, DateTimeKind.Local).AddTicks(97)
                        },
                        new
                        {
                            Id = 3,
                            Action = "Create",
                            Address = "/Role/Create",
                            Controller = "Role",
                            CreatedAt = new DateTime(2026, 6, 4, 9, 25, 43, 644, DateTimeKind.Local).AddTicks(99),
                            Icon = "",
                            Menu = 1,
                            Name = "Rol Ekle",
                            ParentId = 2,
                            Type = "Page",
                            UpdatedAt = new DateTime(2026, 6, 4, 9, 25, 43, 644, DateTimeKind.Local).AddTicks(100)
                        },
                        new
                        {
                            Id = 4,
                            Action = "Edit",
                            Address = "/Role/Edit",
                            Controller = "Role",
                            CreatedAt = new DateTime(2026, 6, 4, 9, 25, 43, 644, DateTimeKind.Local).AddTicks(102),
                            Icon = "",
                            Menu = 0,
                            Name = "Rol Düzenleme",
                            ParentId = 2,
                            Type = "Feature",
                            UpdatedAt = new DateTime(2026, 6, 4, 9, 25, 43, 644, DateTimeKind.Local).AddTicks(102)
                        },
                        new
                        {
                            Id = 5,
                            Action = "Delete",
                            Address = "/Role/Delete",
                            Controller = "Role",
                            CreatedAt = new DateTime(2026, 6, 4, 9, 25, 43, 644, DateTimeKind.Local).AddTicks(104),
                            Icon = "",
                            Menu = 0,
                            Name = "Rol Silme",
                            ParentId = 2,
                            Type = "Feature",
                            UpdatedAt = new DateTime(2026, 6, 4, 9, 25, 43, 644, DateTimeKind.Local).AddTicks(105)
                        },
                        new
                        {
                            Id = 6,
                            Action = "GetById",
                            Address = "/Role/GetById",
                            Controller = "Role",
                            CreatedAt = new DateTime(2026, 6, 4, 9, 25, 43, 644, DateTimeKind.Local).AddTicks(107),
                            Icon = "",
                            Menu = 0,
                            Name = "Id Bazlı Rol Getirme",
                            ParentId = 2,
                            Type = "Feature",
                            UpdatedAt = new DateTime(2026, 6, 4, 9, 25, 43, 644, DateTimeKind.Local).AddTicks(107)
                        },
                        new
                        {
                            Id = 7,
                            Action = "Index",
                            Address = "/Role/Index",
                            Controller = "Role",
                            CreatedAt = new DateTime(2026, 6, 4, 9, 25, 43, 644, DateTimeKind.Local).AddTicks(109),
                            Icon = "",
                            Menu = 1,
                            Name = "Rol Listesi",
                            ParentId = 2,
                            Type = "Page",
                            UpdatedAt = new DateTime(2026, 6, 4, 9, 25, 43, 644, DateTimeKind.Local).AddTicks(109)
                        },
                        new
                        {
                            Id = 8,
                            Action = "GetList",
                            Address = "/Role/GetList",
                            Controller = "Role",
                            CreatedAt = new DateTime(2026, 6, 4, 9, 25, 43, 644, DateTimeKind.Local).AddTicks(111),
                            Icon = "",
                            Menu = 0,
                            Name = "Rol Listesi",
                            ParentId = 2,
                            Type = "Page",
                            UpdatedAt = new DateTime(2026, 6, 4, 9, 25, 43, 644, DateTimeKind.Local).AddTicks(112)
                        },
                        new
                        {
                            Id = 9,
                            Action = "Authentication",
                            Address = "/Role/Authentication",
                            Controller = "Role",
                            CreatedAt = new DateTime(2026, 6, 4, 9, 25, 43, 644, DateTimeKind.Local).AddTicks(191),
                            Icon = "",
                            Menu = 0,
                            Name = "Rol Yetkilendirme",
                            ParentId = 2,
                            Type = "Page",
                            UpdatedAt = new DateTime(2026, 6, 4, 9, 25, 43, 644, DateTimeKind.Local).AddTicks(192)
                        },
                        new
                        {
                            Id = 10,
                            Action = "Index",
                            Address = "/Module/Index",
                            Controller = "Module",
                            CreatedAt = new DateTime(2026, 6, 4, 9, 25, 43, 644, DateTimeKind.Local).AddTicks(194),
                            Icon = "fas fa-align-justify",
                            Menu = 1,
                            Name = "Modül Yönetimi",
                            ParentId = 0,
                            Type = "Category",
                            UpdatedAt = new DateTime(2026, 6, 4, 9, 25, 43, 644, DateTimeKind.Local).AddTicks(195)
                        },
                        new
                        {
                            Id = 11,
                            Action = "Index",
                            Address = "/Module/Index",
                            Controller = "Module",
                            CreatedAt = new DateTime(2026, 6, 4, 9, 25, 43, 644, DateTimeKind.Local).AddTicks(197),
                            Icon = "",
                            Menu = 1,
                            Name = "Modül Listesi",
                            ParentId = 10,
                            Type = "Page",
                            UpdatedAt = new DateTime(2026, 6, 4, 9, 25, 43, 644, DateTimeKind.Local).AddTicks(198)
                        },
                        new
                        {
                            Id = 12,
                            Action = "GetList",
                            Address = "/Module/GetList",
                            Controller = "Module",
                            CreatedAt = new DateTime(2026, 6, 4, 9, 25, 43, 644, DateTimeKind.Local).AddTicks(199),
                            Icon = "",
                            Menu = 0,
                            Name = "Modül Listesi",
                            ParentId = 10,
                            Type = "Feature",
                            UpdatedAt = new DateTime(2026, 6, 4, 9, 25, 43, 644, DateTimeKind.Local).AddTicks(200)
                        },
                        new
                        {
                            Id = 13,
                            Action = "Delete",
                            Address = "/Module/Delete",
                            Controller = "Module",
                            CreatedAt = new DateTime(2026, 6, 4, 9, 25, 43, 644, DateTimeKind.Local).AddTicks(202),
                            Icon = "",
                            Menu = 0,
                            Name = "Modül Silme",
                            ParentId = 10,
                            Type = "Feature",
                            UpdatedAt = new DateTime(2026, 6, 4, 9, 25, 43, 644, DateTimeKind.Local).AddTicks(202)
                        },
                        new
                        {
                            Id = 14,
                            Action = "GetById",
                            Address = "/Module/GetById",
                            Controller = "Module",
                            CreatedAt = new DateTime(2026, 6, 4, 9, 25, 43, 644, DateTimeKind.Local).AddTicks(204),
                            Icon = "",
                            Menu = 10,
                            Name = "Id Bazlı Rol Getirmea",
                            ParentId = 3,
                            Type = "Feature",
                            UpdatedAt = new DateTime(2026, 6, 4, 9, 25, 43, 644, DateTimeKind.Local).AddTicks(204)
                        },
                        new
                        {
                            Id = 15,
                            Action = "Create",
                            Address = "/Module/Create",
                            Controller = "Module",
                            CreatedAt = new DateTime(2026, 6, 4, 9, 25, 43, 644, DateTimeKind.Local).AddTicks(206),
                            Icon = "",
                            Menu = 1,
                            Name = "Modül Ekle",
                            ParentId = 10,
                            Type = "Page",
                            UpdatedAt = new DateTime(2026, 6, 4, 9, 25, 43, 644, DateTimeKind.Local).AddTicks(207)
                        },
                        new
                        {
                            Id = 16,
                            Action = "Index",
                            Address = "/Mail/Index",
                            Controller = "Mail",
                            CreatedAt = new DateTime(2026, 6, 4, 9, 25, 43, 644, DateTimeKind.Local).AddTicks(208),
                            Icon = "icon-mail5 mr-3",
                            Menu = 1,
                            Name = "E-Posta Yönetimi",
                            ParentId = 16,
                            Type = "Category",
                            UpdatedAt = new DateTime(2026, 6, 4, 9, 25, 43, 644, DateTimeKind.Local).AddTicks(209)
                        },
                        new
                        {
                            Id = 17,
                            Action = "Index",
                            Address = "/Mail/Index",
                            Controller = "Mail",
                            CreatedAt = new DateTime(2026, 6, 4, 9, 25, 43, 644, DateTimeKind.Local).AddTicks(210),
                            Icon = "",
                            Menu = 1,
                            Name = "E-Posta Listesi",
                            ParentId = 16,
                            Type = "Page",
                            UpdatedAt = new DateTime(2026, 6, 4, 9, 25, 43, 644, DateTimeKind.Local).AddTicks(211)
                        },
                        new
                        {
                            Id = 18,
                            Action = "GetList",
                            Address = "/Mail/GetList",
                            Controller = "Mail",
                            CreatedAt = new DateTime(2026, 6, 4, 9, 25, 43, 644, DateTimeKind.Local).AddTicks(212),
                            Icon = "",
                            Menu = 0,
                            Name = "E-Posta Listesi",
                            ParentId = 16,
                            Type = "Feature",
                            UpdatedAt = new DateTime(2026, 6, 4, 9, 25, 43, 644, DateTimeKind.Local).AddTicks(213)
                        });
                });

            modelBuilder.Entity("Entity.ModuleRoles", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("ModuleId")
                        .HasColumnType("integer");

                    b.Property<int>("RolId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ModuleId");

                    b.HasIndex("RolId");

                    b.HasIndex("UserId");

                    b.ToTable("ModuleRoles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 6, 4, 9, 25, 43, 644, DateTimeKind.Local).AddTicks(261),
                            ModuleId = 1,
                            RolId = 1,
                            UpdatedAt = new DateTime(2026, 6, 4, 9, 25, 43, 644, DateTimeKind.Local).AddTicks(263),
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 6, 4, 9, 25, 43, 644, DateTimeKind.Local).AddTicks(265),
                            ModuleId = 2,
                            RolId = 1,
                            UpdatedAt = new DateTime(2026, 6, 4, 9, 25, 43, 644, DateTimeKind.Local).AddTicks(265),
                            UserId = 1
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 6, 4, 9, 25, 43, 644, DateTimeKind.Local).AddTicks(267),
                            ModuleId = 3,
                            RolId = 1,
                            UpdatedAt = new DateTime(2026, 6, 4, 9, 25, 43, 644, DateTimeKind.Local).AddTicks(267),
                            UserId = 1
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 6, 4, 9, 25, 43, 644, DateTimeKind.Local).AddTicks(269),
                            ModuleId = 4,
                            RolId = 1,
                            UpdatedAt = new DateTime(2026, 6, 4, 9, 25, 43, 644, DateTimeKind.Local).AddTicks(270),
                            UserId = 1
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2026, 6, 4, 9, 25, 43, 644, DateTimeKind.Local).AddTicks(271),
                            ModuleId = 5,
                            RolId = 1,
                            UpdatedAt = new DateTime(2026, 6, 4, 9, 25, 43, 644, DateTimeKind.Local).AddTicks(272),
                            UserId = 1
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2026, 6, 4, 9, 25, 43, 644, DateTimeKind.Local).AddTicks(273),
                            ModuleId = 6,
                            RolId = 1,
                            UpdatedAt = new DateTime(2026, 6, 4, 9, 25, 43, 644, DateTimeKind.Local).AddTicks(274),
                            UserId = 1
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2026, 6, 4, 9, 25, 43, 644, DateTimeKind.Local).AddTicks(275),
                            ModuleId = 7,
                            RolId = 1,
                            UpdatedAt = new DateTime(2026, 6, 4, 9, 25, 43, 644, DateTimeKind.Local).AddTicks(276),
                            UserId = 1
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2026, 6, 4, 9, 25, 43, 644, DateTimeKind.Local).AddTicks(277),
                            ModuleId = 8,
                            RolId = 1,
                            UpdatedAt = new DateTime(2026, 6, 4, 9, 25, 43, 644, DateTimeKind.Local).AddTicks(278),
                            UserId = 1
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2026, 6, 4, 9, 25, 43, 644, DateTimeKind.Local).AddTicks(279),
                            ModuleId = 9,
                            RolId = 1,
                            UpdatedAt = new DateTime(2026, 6, 4, 9, 25, 43, 644, DateTimeKind.Local).AddTicks(280),
                            UserId = 1
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2026, 6, 4, 9, 25, 43, 644, DateTimeKind.Local).AddTicks(281),
                            ModuleId = 10,
                            RolId = 1,
                            UpdatedAt = new DateTime(2026, 6, 4, 9, 25, 43, 644, DateTimeKind.Local).AddTicks(282),
                            UserId = 1
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2026, 6, 4, 9, 25, 43, 644, DateTimeKind.Local).AddTicks(283),
                            ModuleId = 11,
                            RolId = 1,
                            UpdatedAt = new DateTime(2026, 6, 4, 9, 25, 43, 644, DateTimeKind.Local).AddTicks(284),
                            UserId = 1
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2026, 6, 4, 9, 25, 43, 644, DateTimeKind.Local).AddTicks(285),
                            ModuleId = 12,
                            RolId = 1,
                            UpdatedAt = new DateTime(2026, 6, 4, 9, 25, 43, 644, DateTimeKind.Local).AddTicks(286),
                            UserId = 1
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(2026, 6, 4, 9, 25, 43, 644, DateTimeKind.Local).AddTicks(287),
                            ModuleId = 13,
                            RolId = 1,
                            UpdatedAt = new DateTime(2026, 6, 4, 9, 25, 43, 644, DateTimeKind.Local).AddTicks(287),
                            UserId = 1
                        },
                        new
                        {
                            Id = 14,
                            CreatedAt = new DateTime(2026, 6, 4, 9, 25, 43, 644, DateTimeKind.Local).AddTicks(289),
                            ModuleId = 14,
                            RolId = 1,
                            UpdatedAt = new DateTime(2026, 6, 4, 9, 25, 43, 644, DateTimeKind.Local).AddTicks(289),
                            UserId = 1
                        },
                        new
                        {
                            Id = 15,
                            CreatedAt = new DateTime(2026, 6, 4, 9, 25, 43, 644, DateTimeKind.Local).AddTicks(291),
                            ModuleId = 15,
                            RolId = 1,
                            UpdatedAt = new DateTime(2026, 6, 4, 9, 25, 43, 644, DateTimeKind.Local).AddTicks(291),
                            UserId = 1
                        },
                        new
                        {
                            Id = 16,
                            CreatedAt = new DateTime(2026, 6, 4, 9, 25, 43, 644, DateTimeKind.Local).AddTicks(293),
                            ModuleId = 16,
                            RolId = 1,
                            UpdatedAt = new DateTime(2026, 6, 4, 9, 25, 43, 644, DateTimeKind.Local).AddTicks(293),
                            UserId = 1
                        },
                        new
                        {
                            Id = 17,
                            CreatedAt = new DateTime(2026, 6, 4, 9, 25, 43, 644, DateTimeKind.Local).AddTicks(295),
                            ModuleId = 17,
                            RolId = 1,
                            UpdatedAt = new DateTime(2026, 6, 4, 9, 25, 43, 644, DateTimeKind.Local).AddTicks(295),
                            UserId = 1
                        },
                        new
                        {
                            Id = 18,
                            CreatedAt = new DateTime(2026, 6, 4, 9, 25, 43, 644, DateTimeKind.Local).AddTicks(296),
                            ModuleId = 18,
                            RolId = 1,
                            UpdatedAt = new DateTime(2026, 6, 4, 9, 25, 43, 644, DateTimeKind.Local).AddTicks(297),
                            UserId = 1
                        });
                });

            modelBuilder.Entity("Entity.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Message")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("Entity.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 6, 4, 9, 25, 43, 643, DateTimeKind.Local).AddTicks(8718),
                            Name = "Süper Admin",
                            UpdatedAt = new DateTime(2026, 6, 4, 9, 25, 43, 643, DateTimeKind.Local).AddTicks(8730)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 6, 4, 9, 25, 43, 643, DateTimeKind.Local).AddTicks(8733),
                            Name = "Kullanıcı",
                            UpdatedAt = new DateTime(2026, 6, 4, 9, 25, 43, 643, DateTimeKind.Local).AddTicks(8734)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 6, 4, 9, 25, 43, 643, DateTimeKind.Local).AddTicks(8735),
                            Name = "Demo",
                            UpdatedAt = new DateTime(2026, 6, 4, 9, 25, 43, 643, DateTimeKind.Local).AddTicks(8735)
                        });
                });

            modelBuilder.Entity("Entity.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BirthDate")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("DeviceToken")
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .HasColumnType("text");

                    b.Property<bool>("IlkGiris")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<bool>("KvkkApproved")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<bool>("OnamApproved")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<byte[]>("PasswordHash")
                        .HasColumnType("bytea");

                    b.Property<byte[]>("PasswordSalt")
                        .HasColumnType("bytea");

                    b.Property<string>("Phone")
                        .HasColumnType("text");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IlkGiris = false,
                            KvkkApproved = false,
                            OnamApproved = false,
                            PasswordHash = new byte[] { 243, 140, 44, 28, 19, 46, 225, 236, 163, 104, 164, 39, 122, 228, 47, 168, 165, 143, 110, 187, 149, 120, 165, 114, 52, 159, 240, 221, 57, 76, 37, 216, 109, 24, 231, 153, 18, 166, 77, 63, 33, 126, 127, 26, 120, 39, 147, 85, 229, 83, 72, 188, 40, 7, 178, 71, 39, 246, 9, 193, 18, 247, 139, 217 },
                            PasswordSalt = new byte[] { 216, 93, 211, 214, 24, 81, 233, 149, 40, 41, 131, 51, 228, 206, 105, 205, 147, 142, 216, 151, 85, 54, 111, 117, 41, 248, 121, 244, 155, 159, 208, 190, 150, 127, 50, 2, 69, 221, 135, 13, 148, 174, 148, 194, 116, 170, 28, 241, 251, 47, 33, 214, 25, 131, 24, 199, 167, 241, 138, 54, 237, 183, 250, 42, 36, 3, 251, 223, 113, 54, 215, 31, 245, 232, 223, 131, 203, 135, 57, 33, 93, 82, 4, 245, 144, 221, 5, 128, 151, 79, 31, 3, 97, 184, 239, 233, 84, 180, 51, 63, 44, 150, 202, 139, 14, 20, 30, 215, 9, 119, 161, 246, 115, 24, 8, 132, 194, 33, 186, 228, 140, 0, 235, 203, 192, 37, 110, 50 },
                            Phone = "00000000000",
                            RoleId = 1
                        });
                });

            modelBuilder.Entity("Entity.ModuleRoles", b =>
                {
                    b.HasOne("Entity.Module", "Module")
                        .WithMany("ModuleRoles")
                        .HasForeignKey("ModuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entity.Role", "Role")
                        .WithMany("ModuleRoles")
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entity.User", "User")
                        .WithMany("ModuleRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Module");

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Entity.User", b =>
                {
                    b.HasOne("Entity.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Entity.Module", b =>
                {
                    b.Navigation("ModuleRoles");
                });

            modelBuilder.Entity("Entity.Role", b =>
                {
                    b.Navigation("ModuleRoles");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("Entity.User", b =>
                {
                    b.Navigation("ModuleRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
