// <auto-generated />
using System;
using System.Collections.Generic;
using DataAccessLayer.EntityFramework.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DataAccessLayer.Migrations
{
    [DbContext(typeof(BaseDbContext))]
    [Migration("20260623081427_onbilgilendirme_added")]
    partial class onbilgilendirme_added
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Entity.CozumlemeSoruUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Asama")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<List<Dictionary<string, string>>>("SoruCevap")
                        .HasColumnType("jsonb");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("CozumlemeSoruUsers");
                });

            modelBuilder.Entity("Entity.Module", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .HasColumnType("text");

                    b.Property<string>("Address")
                        .HasColumnType("text");

                    b.Property<string>("Controller")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Icon")
                        .HasColumnType("text");

                    b.Property<int>("Menu")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<int>("ParentId")
                        .HasColumnType("integer");

                    b.Property<string>("Type")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.ToTable("Modules");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Action = "Index",
                            Address = "/Home/Index",
                            Controller = "Home",
                            CreatedAt = new DateTime(2026, 6, 23, 11, 14, 26, 926, DateTimeKind.Local).AddTicks(3294),
                            Icon = "fas fa-home",
                            Menu = 1,
                            Name = "Ana Sayfa",
                            ParentId = 0,
                            Type = "Page",
                            UpdatedAt = new DateTime(2026, 6, 23, 11, 14, 26, 926, DateTimeKind.Local).AddTicks(3296)
                        },
                        new
                        {
                            Id = 2,
                            Action = "Index",
                            Address = "Index",
                            Controller = "Role",
                            CreatedAt = new DateTime(2026, 6, 23, 11, 14, 26, 926, DateTimeKind.Local).AddTicks(3299),
                            Icon = "icon-user-lock",
                            Menu = 1,
                            Name = "Rol Yönetimi",
                            ParentId = 0,
                            Type = "Category",
                            UpdatedAt = new DateTime(2026, 6, 23, 11, 14, 26, 926, DateTimeKind.Local).AddTicks(3299)
                        },
                        new
                        {
                            Id = 3,
                            Action = "Create",
                            Address = "/Role/Create",
                            Controller = "Role",
                            CreatedAt = new DateTime(2026, 6, 23, 11, 14, 26, 926, DateTimeKind.Local).AddTicks(3301),
                            Icon = "",
                            Menu = 1,
                            Name = "Rol Ekle",
                            ParentId = 2,
                            Type = "Page",
                            UpdatedAt = new DateTime(2026, 6, 23, 11, 14, 26, 926, DateTimeKind.Local).AddTicks(3302)
                        },
                        new
                        {
                            Id = 4,
                            Action = "Edit",
                            Address = "/Role/Edit",
                            Controller = "Role",
                            CreatedAt = new DateTime(2026, 6, 23, 11, 14, 26, 926, DateTimeKind.Local).AddTicks(3303),
                            Icon = "",
                            Menu = 0,
                            Name = "Rol Düzenleme",
                            ParentId = 2,
                            Type = "Feature",
                            UpdatedAt = new DateTime(2026, 6, 23, 11, 14, 26, 926, DateTimeKind.Local).AddTicks(3304)
                        },
                        new
                        {
                            Id = 5,
                            Action = "Delete",
                            Address = "/Role/Delete",
                            Controller = "Role",
                            CreatedAt = new DateTime(2026, 6, 23, 11, 14, 26, 926, DateTimeKind.Local).AddTicks(3306),
                            Icon = "",
                            Menu = 0,
                            Name = "Rol Silme",
                            ParentId = 2,
                            Type = "Feature",
                            UpdatedAt = new DateTime(2026, 6, 23, 11, 14, 26, 926, DateTimeKind.Local).AddTicks(3306)
                        },
                        new
                        {
                            Id = 6,
                            Action = "GetById",
                            Address = "/Role/GetById",
                            Controller = "Role",
                            CreatedAt = new DateTime(2026, 6, 23, 11, 14, 26, 926, DateTimeKind.Local).AddTicks(3308),
                            Icon = "",
                            Menu = 0,
                            Name = "Id Bazlı Rol Getirme",
                            ParentId = 2,
                            Type = "Feature",
                            UpdatedAt = new DateTime(2026, 6, 23, 11, 14, 26, 926, DateTimeKind.Local).AddTicks(3308)
                        },
                        new
                        {
                            Id = 7,
                            Action = "/Role/Index",
                            Address = "/Role/Index",
                            Controller = "Role",
                            CreatedAt = new DateTime(2026, 6, 23, 11, 14, 26, 926, DateTimeKind.Local).AddTicks(3310),
                            Icon = "",
                            Menu = 1,
                            Name = "Rol Listesi",
                            ParentId = 2,
                            Type = "Page",
                            UpdatedAt = new DateTime(2026, 6, 23, 11, 14, 26, 926, DateTimeKind.Local).AddTicks(3311)
                        },
                        new
                        {
                            Id = 8,
                            Action = "GetList",
                            Address = "/Role/GetList",
                            Controller = "Role",
                            CreatedAt = new DateTime(2026, 6, 23, 11, 14, 26, 926, DateTimeKind.Local).AddTicks(3313),
                            Icon = "",
                            Menu = 0,
                            Name = "Rol Listesi",
                            ParentId = 2,
                            Type = "Page",
                            UpdatedAt = new DateTime(2026, 6, 23, 11, 14, 26, 926, DateTimeKind.Local).AddTicks(3314)
                        },
                        new
                        {
                            Id = 9,
                            Action = "Authentication",
                            Address = "/Role/Authentication",
                            Controller = "Role",
                            CreatedAt = new DateTime(2026, 6, 23, 11, 14, 26, 926, DateTimeKind.Local).AddTicks(3316),
                            Icon = "",
                            Menu = 0,
                            Name = "Rol Yetkilendirme",
                            ParentId = 2,
                            Type = "Page",
                            UpdatedAt = new DateTime(2026, 6, 23, 11, 14, 26, 926, DateTimeKind.Local).AddTicks(3316)
                        },
                        new
                        {
                            Id = 10,
                            Action = "Index",
                            Address = "/Module/Index",
                            Controller = "Module",
                            CreatedAt = new DateTime(2026, 6, 23, 11, 14, 26, 926, DateTimeKind.Local).AddTicks(3318),
                            Icon = "fas fa-align-justify",
                            Menu = 1,
                            Name = "Modül Yönetimi",
                            ParentId = 0,
                            Type = "Category",
                            UpdatedAt = new DateTime(2026, 6, 23, 11, 14, 26, 926, DateTimeKind.Local).AddTicks(3318)
                        },
                        new
                        {
                            Id = 11,
                            Action = "/Module/Index",
                            Address = "/Module/Index",
                            Controller = "Module",
                            CreatedAt = new DateTime(2026, 6, 23, 11, 14, 26, 926, DateTimeKind.Local).AddTicks(3320),
                            Icon = "",
                            Menu = 1,
                            Name = "Modül Listesi",
                            ParentId = 10,
                            Type = "Page",
                            UpdatedAt = new DateTime(2026, 6, 23, 11, 14, 26, 926, DateTimeKind.Local).AddTicks(3320)
                        },
                        new
                        {
                            Id = 12,
                            Action = "GetList",
                            Address = "/Module/GetList",
                            Controller = "Module",
                            CreatedAt = new DateTime(2026, 6, 23, 11, 14, 26, 926, DateTimeKind.Local).AddTicks(3322),
                            Icon = "",
                            Menu = 0,
                            Name = "Modül Listesi",
                            ParentId = 10,
                            Type = "Feature",
                            UpdatedAt = new DateTime(2026, 6, 23, 11, 14, 26, 926, DateTimeKind.Local).AddTicks(3323)
                        },
                        new
                        {
                            Id = 13,
                            Action = "Delete",
                            Address = "/Module/Delete",
                            Controller = "Module",
                            CreatedAt = new DateTime(2026, 6, 23, 11, 14, 26, 926, DateTimeKind.Local).AddTicks(3324),
                            Icon = "",
                            Menu = 0,
                            Name = "Modül Silme",
                            ParentId = 10,
                            Type = "Feature",
                            UpdatedAt = new DateTime(2026, 6, 23, 11, 14, 26, 926, DateTimeKind.Local).AddTicks(3325)
                        },
                        new
                        {
                            Id = 14,
                            Action = "GetById",
                            Address = "/Module/GetById",
                            Controller = "Module",
                            CreatedAt = new DateTime(2026, 6, 23, 11, 14, 26, 926, DateTimeKind.Local).AddTicks(3326),
                            Icon = "",
                            Menu = 10,
                            Name = "Id Bazlı Rol Getirmea",
                            ParentId = 3,
                            Type = "Feature",
                            UpdatedAt = new DateTime(2026, 6, 23, 11, 14, 26, 926, DateTimeKind.Local).AddTicks(3327)
                        },
                        new
                        {
                            Id = 15,
                            Action = "/Module/Create",
                            Address = "/Module/Create",
                            Controller = "Module",
                            CreatedAt = new DateTime(2026, 6, 23, 11, 14, 26, 926, DateTimeKind.Local).AddTicks(3328),
                            Icon = "",
                            Menu = 1,
                            Name = "Modül Ekle",
                            ParentId = 10,
                            Type = "Page",
                            UpdatedAt = new DateTime(2026, 6, 23, 11, 14, 26, 926, DateTimeKind.Local).AddTicks(3329)
                        },
                        new
                        {
                            Id = 16,
                            Action = "Index",
                            Address = "/Mail/Index",
                            Controller = "Mail",
                            CreatedAt = new DateTime(2026, 6, 23, 11, 14, 26, 926, DateTimeKind.Local).AddTicks(3330),
                            Icon = "icon-mail5 mr-3",
                            Menu = 1,
                            Name = "E-Posta Yönetimi",
                            ParentId = 16,
                            Type = "Category",
                            UpdatedAt = new DateTime(2026, 6, 23, 11, 14, 26, 926, DateTimeKind.Local).AddTicks(3331)
                        },
                        new
                        {
                            Id = 17,
                            Action = "Index",
                            Address = "/Mail/Index",
                            Controller = "Mail",
                            CreatedAt = new DateTime(2026, 6, 23, 11, 14, 26, 926, DateTimeKind.Local).AddTicks(3333),
                            Icon = "",
                            Menu = 1,
                            Name = "E-Posta Listesi",
                            ParentId = 16,
                            Type = "Page",
                            UpdatedAt = new DateTime(2026, 6, 23, 11, 14, 26, 926, DateTimeKind.Local).AddTicks(3334)
                        },
                        new
                        {
                            Id = 18,
                            Action = "GetList",
                            Address = "/Mail/GetList",
                            Controller = "Mail",
                            CreatedAt = new DateTime(2026, 6, 23, 11, 14, 26, 926, DateTimeKind.Local).AddTicks(3335),
                            Icon = "",
                            Menu = 0,
                            Name = "E-Posta Listesi",
                            ParentId = 16,
                            Type = "Feature",
                            UpdatedAt = new DateTime(2026, 6, 23, 11, 14, 26, 926, DateTimeKind.Local).AddTicks(3335)
                        },
                        new
                        {
                            Id = 19,
                            Action = "/kullanici_islemleri",
                            Address = "/User/KullaniciIslemleri",
                            Controller = "User",
                            CreatedAt = new DateTime(2026, 6, 23, 11, 14, 26, 926, DateTimeKind.Local).AddTicks(3337),
                            Icon = "",
                            Menu = 0,
                            Name = "Kullanıcı İşlemleri",
                            ParentId = 16,
                            Type = "Feature",
                            UpdatedAt = new DateTime(2026, 6, 23, 11, 14, 26, 926, DateTimeKind.Local).AddTicks(3337)
                        },
                        new
                        {
                            Id = 20,
                            Action = "Api",
                            Address = "Api",
                            Controller = "Api",
                            CreatedAt = new DateTime(2026, 6, 23, 11, 14, 26, 926, DateTimeKind.Local).AddTicks(3339),
                            Icon = "",
                            Menu = 0,
                            Name = "Api Modules",
                            ParentId = 16,
                            Type = "Feature",
                            UpdatedAt = new DateTime(2026, 6, 23, 11, 14, 26, 926, DateTimeKind.Local).AddTicks(3340)
                        },
                        new
                        {
                            Id = 21,
                            Action = "/kullanici_detay",
                            Address = "/User/Detail",
                            Controller = "User",
                            CreatedAt = new DateTime(2026, 6, 23, 11, 14, 26, 926, DateTimeKind.Local).AddTicks(3341),
                            Icon = "",
                            Menu = 0,
                            Name = "Kullanıcı Detay",
                            ParentId = 16,
                            Type = "Feature",
                            UpdatedAt = new DateTime(2026, 6, 23, 11, 14, 26, 926, DateTimeKind.Local).AddTicks(3342)
                        },
                        new
                        {
                            Id = 22,
                            Action = "Detail",
                            Address = "/User/Detail",
                            Controller = "User",
                            CreatedAt = new DateTime(2026, 6, 23, 11, 14, 26, 926, DateTimeKind.Local).AddTicks(3343),
                            Icon = "",
                            Menu = 0,
                            Name = "User Detail",
                            ParentId = 16,
                            Type = "Feature",
                            UpdatedAt = new DateTime(2026, 6, 23, 11, 14, 26, 926, DateTimeKind.Local).AddTicks(3344)
                        },
                        new
                        {
                            Id = 23,
                            Action = "GetUsers",
                            Address = "/User/GetUsers",
                            Controller = "User",
                            CreatedAt = new DateTime(2026, 6, 23, 11, 14, 26, 926, DateTimeKind.Local).AddTicks(3444),
                            Icon = "",
                            Menu = 0,
                            Name = "User GetUsers",
                            ParentId = 16,
                            Type = "Feature",
                            UpdatedAt = new DateTime(2026, 6, 23, 11, 14, 26, 926, DateTimeKind.Local).AddTicks(3445)
                        },
                        new
                        {
                            Id = 24,
                            Action = "GetUserById",
                            Address = "/User/GetUserById",
                            Controller = "User",
                            CreatedAt = new DateTime(2026, 6, 23, 11, 14, 26, 926, DateTimeKind.Local).AddTicks(3446),
                            Icon = "",
                            Menu = 0,
                            Name = "User GetById",
                            ParentId = 16,
                            Type = "Feature",
                            UpdatedAt = new DateTime(2026, 6, 23, 11, 14, 26, 926, DateTimeKind.Local).AddTicks(3447)
                        },
                        new
                        {
                            Id = 25,
                            Action = "CreateUser",
                            Address = "/User/CreateUser",
                            Controller = "User",
                            CreatedAt = new DateTime(2026, 6, 23, 11, 14, 26, 926, DateTimeKind.Local).AddTicks(3448),
                            Icon = "",
                            Menu = 0,
                            Name = "User CreateUser",
                            ParentId = 16,
                            Type = "Feature",
                            UpdatedAt = new DateTime(2026, 6, 23, 11, 14, 26, 926, DateTimeKind.Local).AddTicks(3449)
                        },
                        new
                        {
                            Id = 26,
                            Action = "UpdateUser",
                            Address = "/User/UpdateUser",
                            Controller = "User",
                            CreatedAt = new DateTime(2026, 6, 23, 11, 14, 26, 926, DateTimeKind.Local).AddTicks(3451),
                            Icon = "",
                            Menu = 0,
                            Name = "User UpdateUser",
                            ParentId = 16,
                            Type = "Feature",
                            UpdatedAt = new DateTime(2026, 6, 23, 11, 14, 26, 926, DateTimeKind.Local).AddTicks(3451)
                        },
                        new
                        {
                            Id = 27,
                            Action = "DeleteUser",
                            Address = "/User/DeleteUser",
                            Controller = "User",
                            CreatedAt = new DateTime(2026, 6, 23, 11, 14, 26, 926, DateTimeKind.Local).AddTicks(3453),
                            Icon = "",
                            Menu = 0,
                            Name = "User DeleteUser",
                            ParentId = 16,
                            Type = "Feature",
                            UpdatedAt = new DateTime(2026, 6, 23, 11, 14, 26, 926, DateTimeKind.Local).AddTicks(3453)
                        },
                        new
                        {
                            Id = 28,
                            Action = "ResetPassword",
                            Address = "/User/ResetPassword",
                            Controller = "User",
                            CreatedAt = new DateTime(2026, 6, 23, 11, 14, 26, 926, DateTimeKind.Local).AddTicks(3455),
                            Icon = "",
                            Menu = 0,
                            Name = "User ResetPassword",
                            ParentId = 16,
                            Type = "Feature",
                            UpdatedAt = new DateTime(2026, 6, 23, 11, 14, 26, 926, DateTimeKind.Local).AddTicks(3455)
                        });
                });

            modelBuilder.Entity("Entity.ModuleRoles", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("ModuleId")
                        .HasColumnType("integer");

                    b.Property<int>("RolId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ModuleId");

                    b.HasIndex("RolId");

                    b.HasIndex("UserId");

                    b.ToTable("ModuleRoles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 6, 23, 11, 14, 26, 926, DateTimeKind.Local).AddTicks(3489),
                            ModuleId = 1,
                            RolId = 1,
                            UpdatedAt = new DateTime(2026, 6, 23, 11, 14, 26, 926, DateTimeKind.Local).AddTicks(3489),
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 6, 23, 11, 14, 26, 926, DateTimeKind.Local).AddTicks(3491),
                            ModuleId = 2,
                            RolId = 1,
                            UpdatedAt = new DateTime(2026, 6, 23, 11, 14, 26, 926, DateTimeKind.Local).AddTicks(3492),
                            UserId = 1
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 6, 23, 11, 14, 26, 926, DateTimeKind.Local).AddTicks(3493),
                            ModuleId = 3,
                            RolId = 1,
                            UpdatedAt = new DateTime(2026, 6, 23, 11, 14, 26, 926, DateTimeKind.Local).AddTicks(3494),
                            UserId = 1
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 6, 23, 11, 14, 26, 926, DateTimeKind.Local).AddTicks(3495),
                            ModuleId = 4,
                            RolId = 1,
                            UpdatedAt = new DateTime(2026, 6, 23, 11, 14, 26, 926, DateTimeKind.Local).AddTicks(3495),
                            UserId = 1
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2026, 6, 23, 11, 14, 26, 926, DateTimeKind.Local).AddTicks(3496),
                            ModuleId = 5,
                            RolId = 1,
                            UpdatedAt = new DateTime(2026, 6, 23, 11, 14, 26, 926, DateTimeKind.Local).AddTicks(3497),
                            UserId = 1
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2026, 6, 23, 11, 14, 26, 926, DateTimeKind.Local).AddTicks(3498),
                            ModuleId = 6,
                            RolId = 1,
                            UpdatedAt = new DateTime(2026, 6, 23, 11, 14, 26, 926, DateTimeKind.Local).AddTicks(3499),
                            UserId = 1
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2026, 6, 23, 11, 14, 26, 926, DateTimeKind.Local).AddTicks(3500),
                            ModuleId = 7,
                            RolId = 1,
                            UpdatedAt = new DateTime(2026, 6, 23, 11, 14, 26, 926, DateTimeKind.Local).AddTicks(3501),
                            UserId = 1
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2026, 6, 23, 11, 14, 26, 926, DateTimeKind.Local).AddTicks(3502),
                            ModuleId = 8,
                            RolId = 1,
                            UpdatedAt = new DateTime(2026, 6, 23, 11, 14, 26, 926, DateTimeKind.Local).AddTicks(3503),
                            UserId = 1
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2026, 6, 23, 11, 14, 26, 926, DateTimeKind.Local).AddTicks(3504),
                            ModuleId = 9,
                            RolId = 1,
                            UpdatedAt = new DateTime(2026, 6, 23, 11, 14, 26, 926, DateTimeKind.Local).AddTicks(3504),
                            UserId = 1
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2026, 6, 23, 11, 14, 26, 926, DateTimeKind.Local).AddTicks(3505),
                            ModuleId = 10,
                            RolId = 1,
                            UpdatedAt = new DateTime(2026, 6, 23, 11, 14, 26, 926, DateTimeKind.Local).AddTicks(3506),
                            UserId = 1
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2026, 6, 23, 11, 14, 26, 926, DateTimeKind.Local).AddTicks(3507),
                            ModuleId = 11,
                            RolId = 1,
                            UpdatedAt = new DateTime(2026, 6, 23, 11, 14, 26, 926, DateTimeKind.Local).AddTicks(3507),
                            UserId = 1
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2026, 6, 23, 11, 14, 26, 926, DateTimeKind.Local).AddTicks(3508),
                            ModuleId = 12,
                            RolId = 1,
                            UpdatedAt = new DateTime(2026, 6, 23, 11, 14, 26, 926, DateTimeKind.Local).AddTicks(3509),
                            UserId = 1
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(2026, 6, 23, 11, 14, 26, 926, DateTimeKind.Local).AddTicks(3510),
                            ModuleId = 13,
                            RolId = 1,
                            UpdatedAt = new DateTime(2026, 6, 23, 11, 14, 26, 926, DateTimeKind.Local).AddTicks(3511),
                            UserId = 1
                        },
                        new
                        {
                            Id = 14,
                            CreatedAt = new DateTime(2026, 6, 23, 11, 14, 26, 926, DateTimeKind.Local).AddTicks(3512),
                            ModuleId = 14,
                            RolId = 1,
                            UpdatedAt = new DateTime(2026, 6, 23, 11, 14, 26, 926, DateTimeKind.Local).AddTicks(3512),
                            UserId = 1
                        },
                        new
                        {
                            Id = 15,
                            CreatedAt = new DateTime(2026, 6, 23, 11, 14, 26, 926, DateTimeKind.Local).AddTicks(3513),
                            ModuleId = 15,
                            RolId = 1,
                            UpdatedAt = new DateTime(2026, 6, 23, 11, 14, 26, 926, DateTimeKind.Local).AddTicks(3514),
                            UserId = 1
                        },
                        new
                        {
                            Id = 16,
                            CreatedAt = new DateTime(2026, 6, 23, 11, 14, 26, 926, DateTimeKind.Local).AddTicks(3516),
                            ModuleId = 16,
                            RolId = 1,
                            UpdatedAt = new DateTime(2026, 6, 23, 11, 14, 26, 926, DateTimeKind.Local).AddTicks(3517),
                            UserId = 1
                        },
                        new
                        {
                            Id = 17,
                            CreatedAt = new DateTime(2026, 6, 23, 11, 14, 26, 926, DateTimeKind.Local).AddTicks(3518),
                            ModuleId = 17,
                            RolId = 1,
                            UpdatedAt = new DateTime(2026, 6, 23, 11, 14, 26, 926, DateTimeKind.Local).AddTicks(3518),
                            UserId = 1
                        },
                        new
                        {
                            Id = 18,
                            CreatedAt = new DateTime(2026, 6, 23, 11, 14, 26, 926, DateTimeKind.Local).AddTicks(3519),
                            ModuleId = 18,
                            RolId = 1,
                            UpdatedAt = new DateTime(2026, 6, 23, 11, 14, 26, 926, DateTimeKind.Local).AddTicks(3520),
                            UserId = 1
                        },
                        new
                        {
                            Id = 19,
                            CreatedAt = new DateTime(2026, 6, 23, 11, 14, 26, 926, DateTimeKind.Local).AddTicks(3521),
                            ModuleId = 19,
                            RolId = 1,
                            UpdatedAt = new DateTime(2026, 6, 23, 11, 14, 26, 926, DateTimeKind.Local).AddTicks(3522),
                            UserId = 1
                        },
                        new
                        {
                            Id = 20,
                            CreatedAt = new DateTime(2026, 6, 23, 11, 14, 26, 926, DateTimeKind.Local).AddTicks(3523),
                            ModuleId = 20,
                            RolId = 1,
                            UpdatedAt = new DateTime(2026, 6, 23, 11, 14, 26, 926, DateTimeKind.Local).AddTicks(3523),
                            UserId = 1
                        },
                        new
                        {
                            Id = 21,
                            CreatedAt = new DateTime(2026, 6, 23, 11, 14, 26, 926, DateTimeKind.Local).AddTicks(3524),
                            ModuleId = 21,
                            RolId = 1,
                            UpdatedAt = new DateTime(2026, 6, 23, 11, 14, 26, 926, DateTimeKind.Local).AddTicks(3525),
                            UserId = 1
                        },
                        new
                        {
                            Id = 22,
                            CreatedAt = new DateTime(2026, 6, 23, 11, 14, 26, 926, DateTimeKind.Local).AddTicks(3526),
                            ModuleId = 22,
                            RolId = 1,
                            UpdatedAt = new DateTime(2026, 6, 23, 11, 14, 26, 926, DateTimeKind.Local).AddTicks(3526),
                            UserId = 1
                        },
                        new
                        {
                            Id = 23,
                            CreatedAt = new DateTime(2026, 6, 23, 11, 14, 26, 926, DateTimeKind.Local).AddTicks(3527),
                            ModuleId = 23,
                            RolId = 1,
                            UpdatedAt = new DateTime(2026, 6, 23, 11, 14, 26, 926, DateTimeKind.Local).AddTicks(3528),
                            UserId = 1
                        },
                        new
                        {
                            Id = 24,
                            CreatedAt = new DateTime(2026, 6, 23, 11, 14, 26, 926, DateTimeKind.Local).AddTicks(3529),
                            ModuleId = 24,
                            RolId = 1,
                            UpdatedAt = new DateTime(2026, 6, 23, 11, 14, 26, 926, DateTimeKind.Local).AddTicks(3530),
                            UserId = 1
                        },
                        new
                        {
                            Id = 25,
                            CreatedAt = new DateTime(2026, 6, 23, 11, 14, 26, 926, DateTimeKind.Local).AddTicks(3531),
                            ModuleId = 25,
                            RolId = 1,
                            UpdatedAt = new DateTime(2026, 6, 23, 11, 14, 26, 926, DateTimeKind.Local).AddTicks(3531),
                            UserId = 1
                        },
                        new
                        {
                            Id = 26,
                            CreatedAt = new DateTime(2026, 6, 23, 11, 14, 26, 926, DateTimeKind.Local).AddTicks(3532),
                            ModuleId = 26,
                            RolId = 1,
                            UpdatedAt = new DateTime(2026, 6, 23, 11, 14, 26, 926, DateTimeKind.Local).AddTicks(3533),
                            UserId = 1
                        },
                        new
                        {
                            Id = 27,
                            CreatedAt = new DateTime(2026, 6, 23, 11, 14, 26, 926, DateTimeKind.Local).AddTicks(3534),
                            ModuleId = 27,
                            RolId = 1,
                            UpdatedAt = new DateTime(2026, 6, 23, 11, 14, 26, 926, DateTimeKind.Local).AddTicks(3534),
                            UserId = 1
                        },
                        new
                        {
                            Id = 28,
                            CreatedAt = new DateTime(2026, 6, 23, 11, 14, 26, 926, DateTimeKind.Local).AddTicks(3535),
                            ModuleId = 28,
                            RolId = 1,
                            UpdatedAt = new DateTime(2026, 6, 23, 11, 14, 26, 926, DateTimeKind.Local).AddTicks(3536),
                            UserId = 1
                        });
                });

            modelBuilder.Entity("Entity.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Message")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("Entity.OnBilgilendirme", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("OnBilgilendirmeMetni")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.ToTable("OnBilgilendirmes");
                });

            modelBuilder.Entity("Entity.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 6, 23, 11, 14, 26, 926, DateTimeKind.Local).AddTicks(2220),
                            Name = "Süper Admin",
                            UpdatedAt = new DateTime(2026, 6, 23, 11, 14, 26, 926, DateTimeKind.Local).AddTicks(2233)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 6, 23, 11, 14, 26, 926, DateTimeKind.Local).AddTicks(2235),
                            Name = "Kullanıcı",
                            UpdatedAt = new DateTime(2026, 6, 23, 11, 14, 26, 926, DateTimeKind.Local).AddTicks(2237)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 6, 23, 11, 14, 26, 926, DateTimeKind.Local).AddTicks(2238),
                            Name = "Demo",
                            UpdatedAt = new DateTime(2026, 6, 23, 11, 14, 26, 926, DateTimeKind.Local).AddTicks(2238)
                        });
                });

            modelBuilder.Entity("Entity.Soru", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<List<Dictionary<string, string>>>("Cevaplar")
                        .HasColumnType("jsonb");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Dictionary<string, string>>("DogruCevap")
                        .HasColumnType("jsonb");

                    b.Property<string>("Hedef")
                        .HasColumnType("text");

                    b.Property<string>("OlcekMaddesi")
                        .HasColumnType("text");

                    b.Property<string>("SoruMetni")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("VideoPath")
                        .HasColumnType("text");

                    b.Property<string>("VideoTranscript")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Sorus");
                });

            modelBuilder.Entity("Entity.SoruUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AciklamaOkumaSuresiSaniye")
                        .HasColumnType("integer");

                    b.Property<int?>("CevaplamaSuresiSaniye")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("Puan")
                        .HasColumnType("integer");

                    b.Property<int>("SoruId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<string>("VerilenCevap")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("SoruId");

                    b.HasIndex("UserId");

                    b.ToTable("SoruUsers");
                });

            modelBuilder.Entity("Entity.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("CozumlemeTamamlandiMi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("DeviceToken")
                        .HasColumnType("text");

                    b.Property<bool>("IlkGiris")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<bool>("KvkkApproved")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("OgrenciNo")
                        .HasColumnType("text");

                    b.Property<bool>("OnamApproved")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<byte[]>("PasswordHash")
                        .HasColumnType("bytea");

                    b.Property<byte[]>("PasswordSalt")
                        .HasColumnType("bytea");

                    b.Property<string>("Phone")
                        .HasColumnType("text");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.Property<bool>("SimulasyonTamamlandiMi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Surname")
                        .HasColumnType("text");

                    b.Property<int?>("ToplamPuan")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("UserName")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CozumlemeTamamlandiMi = false,
                            IlkGiris = false,
                            KvkkApproved = false,
                            OnamApproved = false,
                            PasswordHash = new byte[] { 36, 27, 235, 74, 172, 184, 63, 61, 213, 31, 53, 255, 27, 177, 164, 180, 37, 18, 218, 103, 28, 134, 32, 222, 242, 38, 181, 137, 155, 210, 198, 180, 240, 34, 146, 162, 48, 29, 7, 115, 112, 221, 165, 205, 149, 70, 80, 3, 70, 245, 242, 64, 198, 233, 178, 191, 118, 68, 147, 222, 158, 254, 198, 58 },
                            PasswordSalt = new byte[] { 171, 143, 75, 157, 156, 125, 161, 205, 192, 141, 225, 243, 94, 37, 40, 230, 5, 152, 230, 136, 223, 202, 40, 100, 105, 64, 107, 136, 148, 83, 5, 89, 67, 83, 177, 155, 196, 199, 228, 169, 191, 26, 209, 21, 193, 157, 169, 43, 15, 11, 78, 128, 253, 55, 166, 221, 55, 137, 214, 12, 88, 0, 36, 224, 70, 171, 191, 97, 30, 169, 27, 68, 178, 113, 182, 35, 255, 249, 182, 25, 47, 146, 151, 93, 218, 114, 44, 169, 12, 170, 86, 220, 114, 44, 147, 111, 106, 128, 82, 17, 135, 90, 236, 230, 164, 189, 211, 183, 137, 139, 97, 4, 109, 249, 139, 55, 99, 176, 132, 141, 157, 108, 129, 134, 132, 162, 118, 238 },
                            Phone = "00000000000",
                            RoleId = 1,
                            SimulasyonTamamlandiMi = false
                        });
                });

            modelBuilder.Entity("Entity.CozumlemeSoruUser", b =>
                {
                    b.HasOne("Entity.User", "User")
                        .WithMany("CozumlemeSoruUsers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Entity.ModuleRoles", b =>
                {
                    b.HasOne("Entity.Module", "Module")
                        .WithMany("ModuleRoles")
                        .HasForeignKey("ModuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entity.Role", "Role")
                        .WithMany("ModuleRoles")
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entity.User", "User")
                        .WithMany("ModuleRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Module");

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Entity.SoruUser", b =>
                {
                    b.HasOne("Entity.Soru", "Soru")
                        .WithMany("SoruUsers")
                        .HasForeignKey("SoruId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entity.User", "User")
                        .WithMany("SoruUsers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Soru");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Entity.User", b =>
                {
                    b.HasOne("Entity.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Entity.Module", b =>
                {
                    b.Navigation("ModuleRoles");
                });

            modelBuilder.Entity("Entity.Role", b =>
                {
                    b.Navigation("ModuleRoles");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("Entity.Soru", b =>
                {
                    b.Navigation("SoruUsers");
                });

            modelBuilder.Entity("Entity.User", b =>
                {
                    b.Navigation("CozumlemeSoruUsers");

                    b.Navigation("ModuleRoles");

                    b.Navigation("SoruUsers");
                });
#pragma warning restore 612, 618
        }
    }
}
