// <auto-generated />
using System;
using System.Collections.Generic;
using DataAccessLayer.EntityFramework.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DataAccessLayer.Migrations
{
    [DbContext(typeof(BaseDbContext))]
    [Migration("20260617142041_sorucevaplamasureleriadded")]
    partial class sorucevaplamasureleriadded
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Entity.CozumlemeSoruUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Asama")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<List<Dictionary<string, string>>>("SoruCevap")
                        .HasColumnType("jsonb");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("CozumlemeSoruUsers");
                });

            modelBuilder.Entity("Entity.Module", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .HasColumnType("text");

                    b.Property<string>("Address")
                        .HasColumnType("text");

                    b.Property<string>("Controller")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Icon")
                        .HasColumnType("text");

                    b.Property<int>("Menu")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<int>("ParentId")
                        .HasColumnType("integer");

                    b.Property<string>("Type")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.ToTable("Modules");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Action = "Index",
                            Address = "/Home/Index",
                            Controller = "Home",
                            CreatedAt = new DateTime(2026, 6, 17, 17, 20, 40, 694, DateTimeKind.Local).AddTicks(786),
                            Icon = "fas fa-home",
                            Menu = 1,
                            Name = "Ana Sayfa",
                            ParentId = 0,
                            Type = "Page",
                            UpdatedAt = new DateTime(2026, 6, 17, 17, 20, 40, 694, DateTimeKind.Local).AddTicks(788)
                        },
                        new
                        {
                            Id = 2,
                            Action = "Index",
                            Address = "Index",
                            Controller = "Role",
                            CreatedAt = new DateTime(2026, 6, 17, 17, 20, 40, 694, DateTimeKind.Local).AddTicks(790),
                            Icon = "icon-user-lock",
                            Menu = 1,
                            Name = "Rol Yönetimi",
                            ParentId = 0,
                            Type = "Category",
                            UpdatedAt = new DateTime(2026, 6, 17, 17, 20, 40, 694, DateTimeKind.Local).AddTicks(791)
                        },
                        new
                        {
                            Id = 3,
                            Action = "Create",
                            Address = "/Role/Create",
                            Controller = "Role",
                            CreatedAt = new DateTime(2026, 6, 17, 17, 20, 40, 694, DateTimeKind.Local).AddTicks(793),
                            Icon = "",
                            Menu = 1,
                            Name = "Rol Ekle",
                            ParentId = 2,
                            Type = "Page",
                            UpdatedAt = new DateTime(2026, 6, 17, 17, 20, 40, 694, DateTimeKind.Local).AddTicks(793)
                        },
                        new
                        {
                            Id = 4,
                            Action = "Edit",
                            Address = "/Role/Edit",
                            Controller = "Role",
                            CreatedAt = new DateTime(2026, 6, 17, 17, 20, 40, 694, DateTimeKind.Local).AddTicks(795),
                            Icon = "",
                            Menu = 0,
                            Name = "Rol Düzenleme",
                            ParentId = 2,
                            Type = "Feature",
                            UpdatedAt = new DateTime(2026, 6, 17, 17, 20, 40, 694, DateTimeKind.Local).AddTicks(796)
                        },
                        new
                        {
                            Id = 5,
                            Action = "Delete",
                            Address = "/Role/Delete",
                            Controller = "Role",
                            CreatedAt = new DateTime(2026, 6, 17, 17, 20, 40, 694, DateTimeKind.Local).AddTicks(798),
                            Icon = "",
                            Menu = 0,
                            Name = "Rol Silme",
                            ParentId = 2,
                            Type = "Feature",
                            UpdatedAt = new DateTime(2026, 6, 17, 17, 20, 40, 694, DateTimeKind.Local).AddTicks(798)
                        },
                        new
                        {
                            Id = 6,
                            Action = "GetById",
                            Address = "/Role/GetById",
                            Controller = "Role",
                            CreatedAt = new DateTime(2026, 6, 17, 17, 20, 40, 694, DateTimeKind.Local).AddTicks(800),
                            Icon = "",
                            Menu = 0,
                            Name = "Id Bazlı Rol Getirme",
                            ParentId = 2,
                            Type = "Feature",
                            UpdatedAt = new DateTime(2026, 6, 17, 17, 20, 40, 694, DateTimeKind.Local).AddTicks(800)
                        },
                        new
                        {
                            Id = 7,
                            Action = "/Role/Index",
                            Address = "/Role/Index",
                            Controller = "Role",
                            CreatedAt = new DateTime(2026, 6, 17, 17, 20, 40, 694, DateTimeKind.Local).AddTicks(802),
                            Icon = "",
                            Menu = 1,
                            Name = "Rol Listesi",
                            ParentId = 2,
                            Type = "Page",
                            UpdatedAt = new DateTime(2026, 6, 17, 17, 20, 40, 694, DateTimeKind.Local).AddTicks(802)
                        },
                        new
                        {
                            Id = 8,
                            Action = "GetList",
                            Address = "/Role/GetList",
                            Controller = "Role",
                            CreatedAt = new DateTime(2026, 6, 17, 17, 20, 40, 694, DateTimeKind.Local).AddTicks(804),
                            Icon = "",
                            Menu = 0,
                            Name = "Rol Listesi",
                            ParentId = 2,
                            Type = "Page",
                            UpdatedAt = new DateTime(2026, 6, 17, 17, 20, 40, 694, DateTimeKind.Local).AddTicks(804)
                        },
                        new
                        {
                            Id = 9,
                            Action = "Authentication",
                            Address = "/Role/Authentication",
                            Controller = "Role",
                            CreatedAt = new DateTime(2026, 6, 17, 17, 20, 40, 694, DateTimeKind.Local).AddTicks(806),
                            Icon = "",
                            Menu = 0,
                            Name = "Rol Yetkilendirme",
                            ParentId = 2,
                            Type = "Page",
                            UpdatedAt = new DateTime(2026, 6, 17, 17, 20, 40, 694, DateTimeKind.Local).AddTicks(806)
                        },
                        new
                        {
                            Id = 10,
                            Action = "Index",
                            Address = "/Module/Index",
                            Controller = "Module",
                            CreatedAt = new DateTime(2026, 6, 17, 17, 20, 40, 694, DateTimeKind.Local).AddTicks(808),
                            Icon = "fas fa-align-justify",
                            Menu = 1,
                            Name = "Modül Yönetimi",
                            ParentId = 0,
                            Type = "Category",
                            UpdatedAt = new DateTime(2026, 6, 17, 17, 20, 40, 694, DateTimeKind.Local).AddTicks(808)
                        },
                        new
                        {
                            Id = 11,
                            Action = "/Module/Index",
                            Address = "/Module/Index",
                            Controller = "Module",
                            CreatedAt = new DateTime(2026, 6, 17, 17, 20, 40, 694, DateTimeKind.Local).AddTicks(810),
                            Icon = "",
                            Menu = 1,
                            Name = "Modül Listesi",
                            ParentId = 10,
                            Type = "Page",
                            UpdatedAt = new DateTime(2026, 6, 17, 17, 20, 40, 694, DateTimeKind.Local).AddTicks(810)
                        },
                        new
                        {
                            Id = 12,
                            Action = "GetList",
                            Address = "/Module/GetList",
                            Controller = "Module",
                            CreatedAt = new DateTime(2026, 6, 17, 17, 20, 40, 694, DateTimeKind.Local).AddTicks(812),
                            Icon = "",
                            Menu = 0,
                            Name = "Modül Listesi",
                            ParentId = 10,
                            Type = "Feature",
                            UpdatedAt = new DateTime(2026, 6, 17, 17, 20, 40, 694, DateTimeKind.Local).AddTicks(813)
                        },
                        new
                        {
                            Id = 13,
                            Action = "Delete",
                            Address = "/Module/Delete",
                            Controller = "Module",
                            CreatedAt = new DateTime(2026, 6, 17, 17, 20, 40, 694, DateTimeKind.Local).AddTicks(814),
                            Icon = "",
                            Menu = 0,
                            Name = "Modül Silme",
                            ParentId = 10,
                            Type = "Feature",
                            UpdatedAt = new DateTime(2026, 6, 17, 17, 20, 40, 694, DateTimeKind.Local).AddTicks(815)
                        },
                        new
                        {
                            Id = 14,
                            Action = "GetById",
                            Address = "/Module/GetById",
                            Controller = "Module",
                            CreatedAt = new DateTime(2026, 6, 17, 17, 20, 40, 694, DateTimeKind.Local).AddTicks(816),
                            Icon = "",
                            Menu = 10,
                            Name = "Id Bazlı Rol Getirmea",
                            ParentId = 3,
                            Type = "Feature",
                            UpdatedAt = new DateTime(2026, 6, 17, 17, 20, 40, 694, DateTimeKind.Local).AddTicks(817)
                        },
                        new
                        {
                            Id = 15,
                            Action = "/Module/Create",
                            Address = "/Module/Create",
                            Controller = "Module",
                            CreatedAt = new DateTime(2026, 6, 17, 17, 20, 40, 694, DateTimeKind.Local).AddTicks(818),
                            Icon = "",
                            Menu = 1,
                            Name = "Modül Ekle",
                            ParentId = 10,
                            Type = "Page",
                            UpdatedAt = new DateTime(2026, 6, 17, 17, 20, 40, 694, DateTimeKind.Local).AddTicks(819)
                        },
                        new
                        {
                            Id = 16,
                            Action = "Index",
                            Address = "/Mail/Index",
                            Controller = "Mail",
                            CreatedAt = new DateTime(2026, 6, 17, 17, 20, 40, 694, DateTimeKind.Local).AddTicks(820),
                            Icon = "icon-mail5 mr-3",
                            Menu = 1,
                            Name = "E-Posta Yönetimi",
                            ParentId = 16,
                            Type = "Category",
                            UpdatedAt = new DateTime(2026, 6, 17, 17, 20, 40, 694, DateTimeKind.Local).AddTicks(821)
                        },
                        new
                        {
                            Id = 17,
                            Action = "Index",
                            Address = "/Mail/Index",
                            Controller = "Mail",
                            CreatedAt = new DateTime(2026, 6, 17, 17, 20, 40, 694, DateTimeKind.Local).AddTicks(822),
                            Icon = "",
                            Menu = 1,
                            Name = "E-Posta Listesi",
                            ParentId = 16,
                            Type = "Page",
                            UpdatedAt = new DateTime(2026, 6, 17, 17, 20, 40, 694, DateTimeKind.Local).AddTicks(823)
                        },
                        new
                        {
                            Id = 18,
                            Action = "GetList",
                            Address = "/Mail/GetList",
                            Controller = "Mail",
                            CreatedAt = new DateTime(2026, 6, 17, 17, 20, 40, 694, DateTimeKind.Local).AddTicks(824),
                            Icon = "",
                            Menu = 0,
                            Name = "E-Posta Listesi",
                            ParentId = 16,
                            Type = "Feature",
                            UpdatedAt = new DateTime(2026, 6, 17, 17, 20, 40, 694, DateTimeKind.Local).AddTicks(825)
                        },
                        new
                        {
                            Id = 19,
                            Action = "/kullanici_islemleri",
                            Address = "/User/KullaniciIslemleri",
                            Controller = "User",
                            CreatedAt = new DateTime(2026, 6, 17, 17, 20, 40, 694, DateTimeKind.Local).AddTicks(826),
                            Icon = "",
                            Menu = 0,
                            Name = "Kullanıcı İşlemleri",
                            ParentId = 16,
                            Type = "Feature",
                            UpdatedAt = new DateTime(2026, 6, 17, 17, 20, 40, 694, DateTimeKind.Local).AddTicks(827)
                        },
                        new
                        {
                            Id = 20,
                            Action = "Api",
                            Address = "Api",
                            Controller = "Api",
                            CreatedAt = new DateTime(2026, 6, 17, 17, 20, 40, 694, DateTimeKind.Local).AddTicks(828),
                            Icon = "",
                            Menu = 0,
                            Name = "Api Modules",
                            ParentId = 16,
                            Type = "Feature",
                            UpdatedAt = new DateTime(2026, 6, 17, 17, 20, 40, 694, DateTimeKind.Local).AddTicks(829)
                        },
                        new
                        {
                            Id = 21,
                            Action = "/kullanici_detay",
                            Address = "/User/Detail",
                            Controller = "User",
                            CreatedAt = new DateTime(2026, 6, 17, 17, 20, 40, 694, DateTimeKind.Local).AddTicks(831),
                            Icon = "",
                            Menu = 0,
                            Name = "Kullanıcı Detay",
                            ParentId = 16,
                            Type = "Feature",
                            UpdatedAt = new DateTime(2026, 6, 17, 17, 20, 40, 694, DateTimeKind.Local).AddTicks(831)
                        },
                        new
                        {
                            Id = 22,
                            Action = "Detail",
                            Address = "/User/Detail",
                            Controller = "User",
                            CreatedAt = new DateTime(2026, 6, 17, 17, 20, 40, 694, DateTimeKind.Local).AddTicks(833),
                            Icon = "",
                            Menu = 0,
                            Name = "User Detail",
                            ParentId = 16,
                            Type = "Feature",
                            UpdatedAt = new DateTime(2026, 6, 17, 17, 20, 40, 694, DateTimeKind.Local).AddTicks(833)
                        },
                        new
                        {
                            Id = 23,
                            Action = "GetUsers",
                            Address = "/User/GetUsers",
                            Controller = "User",
                            CreatedAt = new DateTime(2026, 6, 17, 17, 20, 40, 694, DateTimeKind.Local).AddTicks(835),
                            Icon = "",
                            Menu = 0,
                            Name = "User GetUsers",
                            ParentId = 16,
                            Type = "Feature",
                            UpdatedAt = new DateTime(2026, 6, 17, 17, 20, 40, 694, DateTimeKind.Local).AddTicks(835)
                        },
                        new
                        {
                            Id = 24,
                            Action = "GetUserById",
                            Address = "/User/GetUserById",
                            Controller = "User",
                            CreatedAt = new DateTime(2026, 6, 17, 17, 20, 40, 694, DateTimeKind.Local).AddTicks(837),
                            Icon = "",
                            Menu = 0,
                            Name = "User GetById",
                            ParentId = 16,
                            Type = "Feature",
                            UpdatedAt = new DateTime(2026, 6, 17, 17, 20, 40, 694, DateTimeKind.Local).AddTicks(837)
                        },
                        new
                        {
                            Id = 25,
                            Action = "CreateUser",
                            Address = "/User/CreateUser",
                            Controller = "User",
                            CreatedAt = new DateTime(2026, 6, 17, 17, 20, 40, 694, DateTimeKind.Local).AddTicks(839),
                            Icon = "",
                            Menu = 0,
                            Name = "User CreateUser",
                            ParentId = 16,
                            Type = "Feature",
                            UpdatedAt = new DateTime(2026, 6, 17, 17, 20, 40, 694, DateTimeKind.Local).AddTicks(839)
                        },
                        new
                        {
                            Id = 26,
                            Action = "UpdateUser",
                            Address = "/User/UpdateUser",
                            Controller = "User",
                            CreatedAt = new DateTime(2026, 6, 17, 17, 20, 40, 694, DateTimeKind.Local).AddTicks(841),
                            Icon = "",
                            Menu = 0,
                            Name = "User UpdateUser",
                            ParentId = 16,
                            Type = "Feature",
                            UpdatedAt = new DateTime(2026, 6, 17, 17, 20, 40, 694, DateTimeKind.Local).AddTicks(841)
                        },
                        new
                        {
                            Id = 27,
                            Action = "DeleteUser",
                            Address = "/User/DeleteUser",
                            Controller = "User",
                            CreatedAt = new DateTime(2026, 6, 17, 17, 20, 40, 694, DateTimeKind.Local).AddTicks(845),
                            Icon = "",
                            Menu = 0,
                            Name = "User DeleteUser",
                            ParentId = 16,
                            Type = "Feature",
                            UpdatedAt = new DateTime(2026, 6, 17, 17, 20, 40, 694, DateTimeKind.Local).AddTicks(846)
                        },
                        new
                        {
                            Id = 28,
                            Action = "ResetPassword",
                            Address = "/User/ResetPassword",
                            Controller = "User",
                            CreatedAt = new DateTime(2026, 6, 17, 17, 20, 40, 694, DateTimeKind.Local).AddTicks(847),
                            Icon = "",
                            Menu = 0,
                            Name = "User ResetPassword",
                            ParentId = 16,
                            Type = "Feature",
                            UpdatedAt = new DateTime(2026, 6, 17, 17, 20, 40, 694, DateTimeKind.Local).AddTicks(848)
                        });
                });

            modelBuilder.Entity("Entity.ModuleRoles", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("ModuleId")
                        .HasColumnType("integer");

                    b.Property<int>("RolId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ModuleId");

                    b.HasIndex("RolId");

                    b.HasIndex("UserId");

                    b.ToTable("ModuleRoles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 6, 17, 17, 20, 40, 694, DateTimeKind.Local).AddTicks(877),
                            ModuleId = 1,
                            RolId = 1,
                            UpdatedAt = new DateTime(2026, 6, 17, 17, 20, 40, 694, DateTimeKind.Local).AddTicks(878),
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 6, 17, 17, 20, 40, 694, DateTimeKind.Local).AddTicks(879),
                            ModuleId = 2,
                            RolId = 1,
                            UpdatedAt = new DateTime(2026, 6, 17, 17, 20, 40, 694, DateTimeKind.Local).AddTicks(880),
                            UserId = 1
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 6, 17, 17, 20, 40, 694, DateTimeKind.Local).AddTicks(880),
                            ModuleId = 3,
                            RolId = 1,
                            UpdatedAt = new DateTime(2026, 6, 17, 17, 20, 40, 694, DateTimeKind.Local).AddTicks(881),
                            UserId = 1
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 6, 17, 17, 20, 40, 694, DateTimeKind.Local).AddTicks(882),
                            ModuleId = 4,
                            RolId = 1,
                            UpdatedAt = new DateTime(2026, 6, 17, 17, 20, 40, 694, DateTimeKind.Local).AddTicks(883),
                            UserId = 1
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2026, 6, 17, 17, 20, 40, 694, DateTimeKind.Local).AddTicks(884),
                            ModuleId = 5,
                            RolId = 1,
                            UpdatedAt = new DateTime(2026, 6, 17, 17, 20, 40, 694, DateTimeKind.Local).AddTicks(884),
                            UserId = 1
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2026, 6, 17, 17, 20, 40, 694, DateTimeKind.Local).AddTicks(885),
                            ModuleId = 6,
                            RolId = 1,
                            UpdatedAt = new DateTime(2026, 6, 17, 17, 20, 40, 694, DateTimeKind.Local).AddTicks(886),
                            UserId = 1
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2026, 6, 17, 17, 20, 40, 694, DateTimeKind.Local).AddTicks(887),
                            ModuleId = 7,
                            RolId = 1,
                            UpdatedAt = new DateTime(2026, 6, 17, 17, 20, 40, 694, DateTimeKind.Local).AddTicks(887),
                            UserId = 1
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2026, 6, 17, 17, 20, 40, 694, DateTimeKind.Local).AddTicks(888),
                            ModuleId = 8,
                            RolId = 1,
                            UpdatedAt = new DateTime(2026, 6, 17, 17, 20, 40, 694, DateTimeKind.Local).AddTicks(889),
                            UserId = 1
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2026, 6, 17, 17, 20, 40, 694, DateTimeKind.Local).AddTicks(889),
                            ModuleId = 9,
                            RolId = 1,
                            UpdatedAt = new DateTime(2026, 6, 17, 17, 20, 40, 694, DateTimeKind.Local).AddTicks(890),
                            UserId = 1
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2026, 6, 17, 17, 20, 40, 694, DateTimeKind.Local).AddTicks(891),
                            ModuleId = 10,
                            RolId = 1,
                            UpdatedAt = new DateTime(2026, 6, 17, 17, 20, 40, 694, DateTimeKind.Local).AddTicks(892),
                            UserId = 1
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2026, 6, 17, 17, 20, 40, 694, DateTimeKind.Local).AddTicks(892),
                            ModuleId = 11,
                            RolId = 1,
                            UpdatedAt = new DateTime(2026, 6, 17, 17, 20, 40, 694, DateTimeKind.Local).AddTicks(893),
                            UserId = 1
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2026, 6, 17, 17, 20, 40, 694, DateTimeKind.Local).AddTicks(968),
                            ModuleId = 12,
                            RolId = 1,
                            UpdatedAt = new DateTime(2026, 6, 17, 17, 20, 40, 694, DateTimeKind.Local).AddTicks(969),
                            UserId = 1
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(2026, 6, 17, 17, 20, 40, 694, DateTimeKind.Local).AddTicks(971),
                            ModuleId = 13,
                            RolId = 1,
                            UpdatedAt = new DateTime(2026, 6, 17, 17, 20, 40, 694, DateTimeKind.Local).AddTicks(971),
                            UserId = 1
                        },
                        new
                        {
                            Id = 14,
                            CreatedAt = new DateTime(2026, 6, 17, 17, 20, 40, 694, DateTimeKind.Local).AddTicks(972),
                            ModuleId = 14,
                            RolId = 1,
                            UpdatedAt = new DateTime(2026, 6, 17, 17, 20, 40, 694, DateTimeKind.Local).AddTicks(973),
                            UserId = 1
                        },
                        new
                        {
                            Id = 15,
                            CreatedAt = new DateTime(2026, 6, 17, 17, 20, 40, 694, DateTimeKind.Local).AddTicks(974),
                            ModuleId = 15,
                            RolId = 1,
                            UpdatedAt = new DateTime(2026, 6, 17, 17, 20, 40, 694, DateTimeKind.Local).AddTicks(974),
                            UserId = 1
                        },
                        new
                        {
                            Id = 16,
                            CreatedAt = new DateTime(2026, 6, 17, 17, 20, 40, 694, DateTimeKind.Local).AddTicks(975),
                            ModuleId = 16,
                            RolId = 1,
                            UpdatedAt = new DateTime(2026, 6, 17, 17, 20, 40, 694, DateTimeKind.Local).AddTicks(976),
                            UserId = 1
                        },
                        new
                        {
                            Id = 17,
                            CreatedAt = new DateTime(2026, 6, 17, 17, 20, 40, 694, DateTimeKind.Local).AddTicks(977),
                            ModuleId = 17,
                            RolId = 1,
                            UpdatedAt = new DateTime(2026, 6, 17, 17, 20, 40, 694, DateTimeKind.Local).AddTicks(977),
                            UserId = 1
                        },
                        new
                        {
                            Id = 18,
                            CreatedAt = new DateTime(2026, 6, 17, 17, 20, 40, 694, DateTimeKind.Local).AddTicks(978),
                            ModuleId = 18,
                            RolId = 1,
                            UpdatedAt = new DateTime(2026, 6, 17, 17, 20, 40, 694, DateTimeKind.Local).AddTicks(979),
                            UserId = 1
                        },
                        new
                        {
                            Id = 19,
                            CreatedAt = new DateTime(2026, 6, 17, 17, 20, 40, 694, DateTimeKind.Local).AddTicks(980),
                            ModuleId = 19,
                            RolId = 1,
                            UpdatedAt = new DateTime(2026, 6, 17, 17, 20, 40, 694, DateTimeKind.Local).AddTicks(980),
                            UserId = 1
                        },
                        new
                        {
                            Id = 20,
                            CreatedAt = new DateTime(2026, 6, 17, 17, 20, 40, 694, DateTimeKind.Local).AddTicks(981),
                            ModuleId = 20,
                            RolId = 1,
                            UpdatedAt = new DateTime(2026, 6, 17, 17, 20, 40, 694, DateTimeKind.Local).AddTicks(982),
                            UserId = 1
                        },
                        new
                        {
                            Id = 21,
                            CreatedAt = new DateTime(2026, 6, 17, 17, 20, 40, 694, DateTimeKind.Local).AddTicks(983),
                            ModuleId = 21,
                            RolId = 1,
                            UpdatedAt = new DateTime(2026, 6, 17, 17, 20, 40, 694, DateTimeKind.Local).AddTicks(983),
                            UserId = 1
                        },
                        new
                        {
                            Id = 22,
                            CreatedAt = new DateTime(2026, 6, 17, 17, 20, 40, 694, DateTimeKind.Local).AddTicks(984),
                            ModuleId = 22,
                            RolId = 1,
                            UpdatedAt = new DateTime(2026, 6, 17, 17, 20, 40, 694, DateTimeKind.Local).AddTicks(985),
                            UserId = 1
                        },
                        new
                        {
                            Id = 23,
                            CreatedAt = new DateTime(2026, 6, 17, 17, 20, 40, 694, DateTimeKind.Local).AddTicks(986),
                            ModuleId = 23,
                            RolId = 1,
                            UpdatedAt = new DateTime(2026, 6, 17, 17, 20, 40, 694, DateTimeKind.Local).AddTicks(986),
                            UserId = 1
                        },
                        new
                        {
                            Id = 24,
                            CreatedAt = new DateTime(2026, 6, 17, 17, 20, 40, 694, DateTimeKind.Local).AddTicks(987),
                            ModuleId = 24,
                            RolId = 1,
                            UpdatedAt = new DateTime(2026, 6, 17, 17, 20, 40, 694, DateTimeKind.Local).AddTicks(988),
                            UserId = 1
                        },
                        new
                        {
                            Id = 25,
                            CreatedAt = new DateTime(2026, 6, 17, 17, 20, 40, 694, DateTimeKind.Local).AddTicks(989),
                            ModuleId = 25,
                            RolId = 1,
                            UpdatedAt = new DateTime(2026, 6, 17, 17, 20, 40, 694, DateTimeKind.Local).AddTicks(989),
                            UserId = 1
                        },
                        new
                        {
                            Id = 26,
                            CreatedAt = new DateTime(2026, 6, 17, 17, 20, 40, 694, DateTimeKind.Local).AddTicks(990),
                            ModuleId = 26,
                            RolId = 1,
                            UpdatedAt = new DateTime(2026, 6, 17, 17, 20, 40, 694, DateTimeKind.Local).AddTicks(991),
                            UserId = 1
                        },
                        new
                        {
                            Id = 27,
                            CreatedAt = new DateTime(2026, 6, 17, 17, 20, 40, 694, DateTimeKind.Local).AddTicks(992),
                            ModuleId = 27,
                            RolId = 1,
                            UpdatedAt = new DateTime(2026, 6, 17, 17, 20, 40, 694, DateTimeKind.Local).AddTicks(992),
                            UserId = 1
                        },
                        new
                        {
                            Id = 28,
                            CreatedAt = new DateTime(2026, 6, 17, 17, 20, 40, 694, DateTimeKind.Local).AddTicks(993),
                            ModuleId = 28,
                            RolId = 1,
                            UpdatedAt = new DateTime(2026, 6, 17, 17, 20, 40, 694, DateTimeKind.Local).AddTicks(994),
                            UserId = 1
                        });
                });

            modelBuilder.Entity("Entity.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Message")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("Entity.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 6, 17, 17, 20, 40, 693, DateTimeKind.Local).AddTicks(9665),
                            Name = "Süper Admin",
                            UpdatedAt = new DateTime(2026, 6, 17, 17, 20, 40, 693, DateTimeKind.Local).AddTicks(9681)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 6, 17, 17, 20, 40, 693, DateTimeKind.Local).AddTicks(9682),
                            Name = "Kullanıcı",
                            UpdatedAt = new DateTime(2026, 6, 17, 17, 20, 40, 693, DateTimeKind.Local).AddTicks(9683)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 6, 17, 17, 20, 40, 693, DateTimeKind.Local).AddTicks(9684),
                            Name = "Demo",
                            UpdatedAt = new DateTime(2026, 6, 17, 17, 20, 40, 693, DateTimeKind.Local).AddTicks(9684)
                        });
                });

            modelBuilder.Entity("Entity.Soru", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<List<Dictionary<string, string>>>("Cevaplar")
                        .HasColumnType("jsonb");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Dictionary<string, string>>("DogruCevap")
                        .HasColumnType("jsonb");

                    b.Property<string>("Hedef")
                        .HasColumnType("text");

                    b.Property<string>("OlcekMaddesi")
                        .HasColumnType("text");

                    b.Property<string>("SoruMetni")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("VideoPath")
                        .HasColumnType("text");

                    b.Property<string>("VideoTranscript")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Sorus");
                });

            modelBuilder.Entity("Entity.SoruUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AciklamaOkumaSuresiSaniye")
                        .HasColumnType("integer");

                    b.Property<int?>("CevaplamaSuresiSaniye")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("Puan")
                        .HasColumnType("integer");

                    b.Property<int>("SoruId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<string>("VerilenCevap")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("SoruId");

                    b.HasIndex("UserId");

                    b.ToTable("SoruUsers");
                });

            modelBuilder.Entity("Entity.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("CozumlemeTamamlandiMi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("DeviceToken")
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .HasColumnType("text");

                    b.Property<bool>("IlkGiris")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<bool>("KvkkApproved")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("OgrenciNo")
                        .HasColumnType("text");

                    b.Property<bool>("OnamApproved")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<byte[]>("PasswordHash")
                        .HasColumnType("bytea");

                    b.Property<byte[]>("PasswordSalt")
                        .HasColumnType("bytea");

                    b.Property<string>("Phone")
                        .HasColumnType("text");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.Property<bool>("SimulasyonTamamlandiMi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Surname")
                        .HasColumnType("text");

                    b.Property<int?>("ToplamPuan")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("UserName")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CozumlemeTamamlandiMi = false,
                            IlkGiris = false,
                            KvkkApproved = false,
                            OnamApproved = false,
                            PasswordHash = new byte[] { 201, 211, 23, 84, 149, 180, 70, 138, 199, 121, 154, 80, 129, 64, 51, 202, 219, 221, 153, 203, 172, 79, 211, 248, 253, 5, 17, 156, 140, 129, 247, 29, 95, 33, 222, 145, 166, 40, 35, 48, 175, 224, 163, 59, 215, 215, 44, 190, 223, 90, 158, 50, 145, 134, 233, 194, 22, 32, 114, 235, 203, 186, 140, 28 },
                            PasswordSalt = new byte[] { 109, 248, 169, 114, 220, 141, 23, 210, 154, 184, 190, 246, 168, 254, 172, 232, 169, 232, 186, 163, 112, 133, 212, 203, 248, 94, 100, 1, 57, 56, 228, 64, 246, 127, 84, 225, 42, 121, 229, 152, 254, 65, 40, 147, 169, 136, 144, 28, 120, 237, 232, 86, 159, 89, 208, 196, 139, 149, 15, 213, 162, 104, 235, 219, 169, 76, 84, 168, 240, 77, 66, 159, 181, 109, 228, 180, 249, 175, 224, 100, 0, 89, 77, 189, 150, 224, 201, 241, 80, 136, 124, 9, 244, 161, 65, 110, 25, 138, 210, 221, 18, 36, 232, 180, 240, 196, 157, 230, 110, 104, 147, 108, 242, 254, 207, 67, 43, 8, 21, 6, 129, 177, 64, 95, 239, 208, 156, 205 },
                            Phone = "00000000000",
                            RoleId = 1,
                            SimulasyonTamamlandiMi = false
                        });
                });

            modelBuilder.Entity("Entity.CozumlemeSoruUser", b =>
                {
                    b.HasOne("Entity.User", "User")
                        .WithMany("CozumlemeSoruUsers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Entity.ModuleRoles", b =>
                {
                    b.HasOne("Entity.Module", "Module")
                        .WithMany("ModuleRoles")
                        .HasForeignKey("ModuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entity.Role", "Role")
                        .WithMany("ModuleRoles")
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entity.User", "User")
                        .WithMany("ModuleRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Module");

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Entity.SoruUser", b =>
                {
                    b.HasOne("Entity.Soru", "Soru")
                        .WithMany("SoruUsers")
                        .HasForeignKey("SoruId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entity.User", "User")
                        .WithMany("SoruUsers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Soru");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Entity.User", b =>
                {
                    b.HasOne("Entity.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Entity.Module", b =>
                {
                    b.Navigation("ModuleRoles");
                });

            modelBuilder.Entity("Entity.Role", b =>
                {
                    b.Navigation("ModuleRoles");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("Entity.Soru", b =>
                {
                    b.Navigation("SoruUsers");
                });

            modelBuilder.Entity("Entity.User", b =>
                {
                    b.Navigation("CozumlemeSoruUsers");

                    b.Navigation("ModuleRoles");

                    b.Navigation("SoruUsers");
                });
#pragma warning restore 612, 618
        }
    }
}
