// <auto-generated />
using System;
using System.Collections.Generic;
using DataAccessLayer.EntityFramework.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DataAccessLayer.Migrations
{
    [DbContext(typeof(BaseDbContext))]
    partial class BaseDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Entity.CozumlemeSoruUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Asama")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<List<Dictionary<string, string>>>("SoruCevap")
                        .HasColumnType("jsonb");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("CozumlemeSoruUsers");
                });

            modelBuilder.Entity("Entity.Module", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .HasColumnType("text");

                    b.Property<string>("Address")
                        .HasColumnType("text");

                    b.Property<string>("Controller")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Icon")
                        .HasColumnType("text");

                    b.Property<int>("Menu")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<int>("ParentId")
                        .HasColumnType("integer");

                    b.Property<string>("Type")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.ToTable("Modules");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Action = "Index",
                            Address = "/Home/Index",
                            Controller = "Home",
                            CreatedAt = new DateTime(2026, 6, 5, 13, 19, 45, 921, DateTimeKind.Local).AddTicks(2738),
                            Icon = "fas fa-home",
                            Menu = 1,
                            Name = "Ana Sayfa",
                            ParentId = 0,
                            Type = "Page",
                            UpdatedAt = new DateTime(2026, 6, 5, 13, 19, 45, 921, DateTimeKind.Local).AddTicks(2740)
                        },
                        new
                        {
                            Id = 2,
                            Action = "Index",
                            Address = "Index",
                            Controller = "Role",
                            CreatedAt = new DateTime(2026, 6, 5, 13, 19, 45, 921, DateTimeKind.Local).AddTicks(2743),
                            Icon = "icon-user-lock",
                            Menu = 1,
                            Name = "Rol Yönetimi",
                            ParentId = 0,
                            Type = "Category",
                            UpdatedAt = new DateTime(2026, 6, 5, 13, 19, 45, 921, DateTimeKind.Local).AddTicks(2744)
                        },
                        new
                        {
                            Id = 3,
                            Action = "Create",
                            Address = "/Role/Create",
                            Controller = "Role",
                            CreatedAt = new DateTime(2026, 6, 5, 13, 19, 45, 921, DateTimeKind.Local).AddTicks(2746),
                            Icon = "",
                            Menu = 1,
                            Name = "Rol Ekle",
                            ParentId = 2,
                            Type = "Page",
                            UpdatedAt = new DateTime(2026, 6, 5, 13, 19, 45, 921, DateTimeKind.Local).AddTicks(2746)
                        },
                        new
                        {
                            Id = 4,
                            Action = "Edit",
                            Address = "/Role/Edit",
                            Controller = "Role",
                            CreatedAt = new DateTime(2026, 6, 5, 13, 19, 45, 921, DateTimeKind.Local).AddTicks(2748),
                            Icon = "",
                            Menu = 0,
                            Name = "Rol Düzenleme",
                            ParentId = 2,
                            Type = "Feature",
                            UpdatedAt = new DateTime(2026, 6, 5, 13, 19, 45, 921, DateTimeKind.Local).AddTicks(2748)
                        },
                        new
                        {
                            Id = 5,
                            Action = "Delete",
                            Address = "/Role/Delete",
                            Controller = "Role",
                            CreatedAt = new DateTime(2026, 6, 5, 13, 19, 45, 921, DateTimeKind.Local).AddTicks(2750),
                            Icon = "",
                            Menu = 0,
                            Name = "Rol Silme",
                            ParentId = 2,
                            Type = "Feature",
                            UpdatedAt = new DateTime(2026, 6, 5, 13, 19, 45, 921, DateTimeKind.Local).AddTicks(2750)
                        },
                        new
                        {
                            Id = 6,
                            Action = "GetById",
                            Address = "/Role/GetById",
                            Controller = "Role",
                            CreatedAt = new DateTime(2026, 6, 5, 13, 19, 45, 921, DateTimeKind.Local).AddTicks(2751),
                            Icon = "",
                            Menu = 0,
                            Name = "Id Bazlı Rol Getirme",
                            ParentId = 2,
                            Type = "Feature",
                            UpdatedAt = new DateTime(2026, 6, 5, 13, 19, 45, 921, DateTimeKind.Local).AddTicks(2752)
                        },
                        new
                        {
                            Id = 7,
                            Action = "/Role/Index",
                            Address = "/Role/Index",
                            Controller = "Role",
                            CreatedAt = new DateTime(2026, 6, 5, 13, 19, 45, 921, DateTimeKind.Local).AddTicks(2753),
                            Icon = "",
                            Menu = 1,
                            Name = "Rol Listesi",
                            ParentId = 2,
                            Type = "Page",
                            UpdatedAt = new DateTime(2026, 6, 5, 13, 19, 45, 921, DateTimeKind.Local).AddTicks(2754)
                        },
                        new
                        {
                            Id = 8,
                            Action = "GetList",
                            Address = "/Role/GetList",
                            Controller = "Role",
                            CreatedAt = new DateTime(2026, 6, 5, 13, 19, 45, 921, DateTimeKind.Local).AddTicks(2755),
                            Icon = "",
                            Menu = 0,
                            Name = "Rol Listesi",
                            ParentId = 2,
                            Type = "Page",
                            UpdatedAt = new DateTime(2026, 6, 5, 13, 19, 45, 921, DateTimeKind.Local).AddTicks(2755)
                        },
                        new
                        {
                            Id = 9,
                            Action = "Authentication",
                            Address = "/Role/Authentication",
                            Controller = "Role",
                            CreatedAt = new DateTime(2026, 6, 5, 13, 19, 45, 921, DateTimeKind.Local).AddTicks(2757),
                            Icon = "",
                            Menu = 0,
                            Name = "Rol Yetkilendirme",
                            ParentId = 2,
                            Type = "Page",
                            UpdatedAt = new DateTime(2026, 6, 5, 13, 19, 45, 921, DateTimeKind.Local).AddTicks(2757)
                        },
                        new
                        {
                            Id = 10,
                            Action = "Index",
                            Address = "/Module/Index",
                            Controller = "Module",
                            CreatedAt = new DateTime(2026, 6, 5, 13, 19, 45, 921, DateTimeKind.Local).AddTicks(2758),
                            Icon = "fas fa-align-justify",
                            Menu = 1,
                            Name = "Modül Yönetimi",
                            ParentId = 0,
                            Type = "Category",
                            UpdatedAt = new DateTime(2026, 6, 5, 13, 19, 45, 921, DateTimeKind.Local).AddTicks(2759)
                        },
                        new
                        {
                            Id = 11,
                            Action = "/Module/Index",
                            Address = "/Module/Index",
                            Controller = "Module",
                            CreatedAt = new DateTime(2026, 6, 5, 13, 19, 45, 921, DateTimeKind.Local).AddTicks(2760),
                            Icon = "",
                            Menu = 1,
                            Name = "Modül Listesi",
                            ParentId = 10,
                            Type = "Page",
                            UpdatedAt = new DateTime(2026, 6, 5, 13, 19, 45, 921, DateTimeKind.Local).AddTicks(2761)
                        },
                        new
                        {
                            Id = 12,
                            Action = "GetList",
                            Address = "/Module/GetList",
                            Controller = "Module",
                            CreatedAt = new DateTime(2026, 6, 5, 13, 19, 45, 921, DateTimeKind.Local).AddTicks(2762),
                            Icon = "",
                            Menu = 0,
                            Name = "Modül Listesi",
                            ParentId = 10,
                            Type = "Feature",
                            UpdatedAt = new DateTime(2026, 6, 5, 13, 19, 45, 921, DateTimeKind.Local).AddTicks(2765)
                        },
                        new
                        {
                            Id = 13,
                            Action = "Delete",
                            Address = "/Module/Delete",
                            Controller = "Module",
                            CreatedAt = new DateTime(2026, 6, 5, 13, 19, 45, 921, DateTimeKind.Local).AddTicks(2767),
                            Icon = "",
                            Menu = 0,
                            Name = "Modül Silme",
                            ParentId = 10,
                            Type = "Feature",
                            UpdatedAt = new DateTime(2026, 6, 5, 13, 19, 45, 921, DateTimeKind.Local).AddTicks(2767)
                        },
                        new
                        {
                            Id = 14,
                            Action = "GetById",
                            Address = "/Module/GetById",
                            Controller = "Module",
                            CreatedAt = new DateTime(2026, 6, 5, 13, 19, 45, 921, DateTimeKind.Local).AddTicks(2768),
                            Icon = "",
                            Menu = 10,
                            Name = "Id Bazlı Rol Getirmea",
                            ParentId = 3,
                            Type = "Feature",
                            UpdatedAt = new DateTime(2026, 6, 5, 13, 19, 45, 921, DateTimeKind.Local).AddTicks(2769)
                        },
                        new
                        {
                            Id = 15,
                            Action = "/Module/Create",
                            Address = "/Module/Create",
                            Controller = "Module",
                            CreatedAt = new DateTime(2026, 6, 5, 13, 19, 45, 921, DateTimeKind.Local).AddTicks(2770),
                            Icon = "",
                            Menu = 1,
                            Name = "Modül Ekle",
                            ParentId = 10,
                            Type = "Page",
                            UpdatedAt = new DateTime(2026, 6, 5, 13, 19, 45, 921, DateTimeKind.Local).AddTicks(2771)
                        },
                        new
                        {
                            Id = 16,
                            Action = "Index",
                            Address = "/Mail/Index",
                            Controller = "Mail",
                            CreatedAt = new DateTime(2026, 6, 5, 13, 19, 45, 921, DateTimeKind.Local).AddTicks(2772),
                            Icon = "icon-mail5 mr-3",
                            Menu = 1,
                            Name = "E-Posta Yönetimi",
                            ParentId = 16,
                            Type = "Category",
                            UpdatedAt = new DateTime(2026, 6, 5, 13, 19, 45, 921, DateTimeKind.Local).AddTicks(2772)
                        },
                        new
                        {
                            Id = 17,
                            Action = "Index",
                            Address = "/Mail/Index",
                            Controller = "Mail",
                            CreatedAt = new DateTime(2026, 6, 5, 13, 19, 45, 921, DateTimeKind.Local).AddTicks(2774),
                            Icon = "",
                            Menu = 1,
                            Name = "E-Posta Listesi",
                            ParentId = 16,
                            Type = "Page",
                            UpdatedAt = new DateTime(2026, 6, 5, 13, 19, 45, 921, DateTimeKind.Local).AddTicks(2774)
                        },
                        new
                        {
                            Id = 18,
                            Action = "GetList",
                            Address = "/Mail/GetList",
                            Controller = "Mail",
                            CreatedAt = new DateTime(2026, 6, 5, 13, 19, 45, 921, DateTimeKind.Local).AddTicks(2775),
                            Icon = "",
                            Menu = 0,
                            Name = "E-Posta Listesi",
                            ParentId = 16,
                            Type = "Feature",
                            UpdatedAt = new DateTime(2026, 6, 5, 13, 19, 45, 921, DateTimeKind.Local).AddTicks(2776)
                        },
                        new
                        {
                            Id = 19,
                            Action = "/kullanici_islemleri",
                            Address = "/User/KullaniciIslemleri",
                            Controller = "User",
                            CreatedAt = new DateTime(2026, 6, 5, 13, 19, 45, 921, DateTimeKind.Local).AddTicks(2777),
                            Icon = "",
                            Menu = 0,
                            Name = "Kullanıcı İşlemleri",
                            ParentId = 16,
                            Type = "Feature",
                            UpdatedAt = new DateTime(2026, 6, 5, 13, 19, 45, 921, DateTimeKind.Local).AddTicks(2777)
                        },
                        new
                        {
                            Id = 20,
                            Action = "Api",
                            Address = "Api",
                            Controller = "Api",
                            CreatedAt = new DateTime(2026, 6, 5, 13, 19, 45, 921, DateTimeKind.Local).AddTicks(2779),
                            Icon = "",
                            Menu = 0,
                            Name = "Api Modules",
                            ParentId = 16,
                            Type = "Feature",
                            UpdatedAt = new DateTime(2026, 6, 5, 13, 19, 45, 921, DateTimeKind.Local).AddTicks(2779)
                        },
                        new
                        {
                            Id = 21,
                            Action = "/kullanici_detay",
                            Address = "/User/Detail",
                            Controller = "User",
                            CreatedAt = new DateTime(2026, 6, 5, 13, 19, 45, 921, DateTimeKind.Local).AddTicks(2781),
                            Icon = "",
                            Menu = 0,
                            Name = "Kullanıcı Detay",
                            ParentId = 16,
                            Type = "Feature",
                            UpdatedAt = new DateTime(2026, 6, 5, 13, 19, 45, 921, DateTimeKind.Local).AddTicks(2782)
                        },
                        new
                        {
                            Id = 22,
                            Action = "Detail",
                            Address = "/User/Detail",
                            Controller = "User",
                            CreatedAt = new DateTime(2026, 6, 5, 13, 19, 45, 921, DateTimeKind.Local).AddTicks(2783),
                            Icon = "",
                            Menu = 0,
                            Name = "User Detail",
                            ParentId = 16,
                            Type = "Feature",
                            UpdatedAt = new DateTime(2026, 6, 5, 13, 19, 45, 921, DateTimeKind.Local).AddTicks(2783)
                        },
                        new
                        {
                            Id = 23,
                            Action = "GetUsers",
                            Address = "/User/GetUsers",
                            Controller = "User",
                            CreatedAt = new DateTime(2026, 6, 5, 13, 19, 45, 921, DateTimeKind.Local).AddTicks(2785),
                            Icon = "",
                            Menu = 0,
                            Name = "User GetUsers",
                            ParentId = 16,
                            Type = "Feature",
                            UpdatedAt = new DateTime(2026, 6, 5, 13, 19, 45, 921, DateTimeKind.Local).AddTicks(2785)
                        },
                        new
                        {
                            Id = 24,
                            Action = "GetUserById",
                            Address = "/User/GetUserById",
                            Controller = "User",
                            CreatedAt = new DateTime(2026, 6, 5, 13, 19, 45, 921, DateTimeKind.Local).AddTicks(2786),
                            Icon = "",
                            Menu = 0,
                            Name = "User GetById",
                            ParentId = 16,
                            Type = "Feature",
                            UpdatedAt = new DateTime(2026, 6, 5, 13, 19, 45, 921, DateTimeKind.Local).AddTicks(2787)
                        },
                        new
                        {
                            Id = 25,
                            Action = "CreateUser",
                            Address = "/User/CreateUser",
                            Controller = "User",
                            CreatedAt = new DateTime(2026, 6, 5, 13, 19, 45, 921, DateTimeKind.Local).AddTicks(2788),
                            Icon = "",
                            Menu = 0,
                            Name = "User CreateUser",
                            ParentId = 16,
                            Type = "Feature",
                            UpdatedAt = new DateTime(2026, 6, 5, 13, 19, 45, 921, DateTimeKind.Local).AddTicks(2789)
                        },
                        new
                        {
                            Id = 26,
                            Action = "UpdateUser",
                            Address = "/User/UpdateUser",
                            Controller = "User",
                            CreatedAt = new DateTime(2026, 6, 5, 13, 19, 45, 921, DateTimeKind.Local).AddTicks(2790),
                            Icon = "",
                            Menu = 0,
                            Name = "User UpdateUser",
                            ParentId = 16,
                            Type = "Feature",
                            UpdatedAt = new DateTime(2026, 6, 5, 13, 19, 45, 921, DateTimeKind.Local).AddTicks(2790)
                        },
                        new
                        {
                            Id = 27,
                            Action = "DeleteUser",
                            Address = "/User/DeleteUser",
                            Controller = "User",
                            CreatedAt = new DateTime(2026, 6, 5, 13, 19, 45, 921, DateTimeKind.Local).AddTicks(2792),
                            Icon = "",
                            Menu = 0,
                            Name = "User DeleteUser",
                            ParentId = 16,
                            Type = "Feature",
                            UpdatedAt = new DateTime(2026, 6, 5, 13, 19, 45, 921, DateTimeKind.Local).AddTicks(2792)
                        },
                        new
                        {
                            Id = 28,
                            Action = "ResetPassword",
                            Address = "/User/ResetPassword",
                            Controller = "User",
                            CreatedAt = new DateTime(2026, 6, 5, 13, 19, 45, 921, DateTimeKind.Local).AddTicks(2793),
                            Icon = "",
                            Menu = 0,
                            Name = "User ResetPassword",
                            ParentId = 16,
                            Type = "Feature",
                            UpdatedAt = new DateTime(2026, 6, 5, 13, 19, 45, 921, DateTimeKind.Local).AddTicks(2794)
                        });
                });

            modelBuilder.Entity("Entity.ModuleRoles", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("ModuleId")
                        .HasColumnType("integer");

                    b.Property<int>("RolId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ModuleId");

                    b.HasIndex("RolId");

                    b.HasIndex("UserId");

                    b.ToTable("ModuleRoles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 6, 5, 13, 19, 45, 921, DateTimeKind.Local).AddTicks(2819),
                            ModuleId = 1,
                            RolId = 1,
                            UpdatedAt = new DateTime(2026, 6, 5, 13, 19, 45, 921, DateTimeKind.Local).AddTicks(2820),
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 6, 5, 13, 19, 45, 921, DateTimeKind.Local).AddTicks(2821),
                            ModuleId = 2,
                            RolId = 1,
                            UpdatedAt = new DateTime(2026, 6, 5, 13, 19, 45, 921, DateTimeKind.Local).AddTicks(2821),
                            UserId = 1
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 6, 5, 13, 19, 45, 921, DateTimeKind.Local).AddTicks(2822),
                            ModuleId = 3,
                            RolId = 1,
                            UpdatedAt = new DateTime(2026, 6, 5, 13, 19, 45, 921, DateTimeKind.Local).AddTicks(2823),
                            UserId = 1
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 6, 5, 13, 19, 45, 921, DateTimeKind.Local).AddTicks(2824),
                            ModuleId = 4,
                            RolId = 1,
                            UpdatedAt = new DateTime(2026, 6, 5, 13, 19, 45, 921, DateTimeKind.Local).AddTicks(2824),
                            UserId = 1
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2026, 6, 5, 13, 19, 45, 921, DateTimeKind.Local).AddTicks(2825),
                            ModuleId = 5,
                            RolId = 1,
                            UpdatedAt = new DateTime(2026, 6, 5, 13, 19, 45, 921, DateTimeKind.Local).AddTicks(2826),
                            UserId = 1
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2026, 6, 5, 13, 19, 45, 921, DateTimeKind.Local).AddTicks(2826),
                            ModuleId = 6,
                            RolId = 1,
                            UpdatedAt = new DateTime(2026, 6, 5, 13, 19, 45, 921, DateTimeKind.Local).AddTicks(2827),
                            UserId = 1
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2026, 6, 5, 13, 19, 45, 921, DateTimeKind.Local).AddTicks(2828),
                            ModuleId = 7,
                            RolId = 1,
                            UpdatedAt = new DateTime(2026, 6, 5, 13, 19, 45, 921, DateTimeKind.Local).AddTicks(2828),
                            UserId = 1
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2026, 6, 5, 13, 19, 45, 921, DateTimeKind.Local).AddTicks(2829),
                            ModuleId = 8,
                            RolId = 1,
                            UpdatedAt = new DateTime(2026, 6, 5, 13, 19, 45, 921, DateTimeKind.Local).AddTicks(2830),
                            UserId = 1
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2026, 6, 5, 13, 19, 45, 921, DateTimeKind.Local).AddTicks(2831),
                            ModuleId = 9,
                            RolId = 1,
                            UpdatedAt = new DateTime(2026, 6, 5, 13, 19, 45, 921, DateTimeKind.Local).AddTicks(2831),
                            UserId = 1
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2026, 6, 5, 13, 19, 45, 921, DateTimeKind.Local).AddTicks(2832),
                            ModuleId = 10,
                            RolId = 1,
                            UpdatedAt = new DateTime(2026, 6, 5, 13, 19, 45, 921, DateTimeKind.Local).AddTicks(2832),
                            UserId = 1
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2026, 6, 5, 13, 19, 45, 921, DateTimeKind.Local).AddTicks(2833),
                            ModuleId = 11,
                            RolId = 1,
                            UpdatedAt = new DateTime(2026, 6, 5, 13, 19, 45, 921, DateTimeKind.Local).AddTicks(2834),
                            UserId = 1
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2026, 6, 5, 13, 19, 45, 921, DateTimeKind.Local).AddTicks(2835),
                            ModuleId = 12,
                            RolId = 1,
                            UpdatedAt = new DateTime(2026, 6, 5, 13, 19, 45, 921, DateTimeKind.Local).AddTicks(2835),
                            UserId = 1
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(2026, 6, 5, 13, 19, 45, 921, DateTimeKind.Local).AddTicks(2837),
                            ModuleId = 13,
                            RolId = 1,
                            UpdatedAt = new DateTime(2026, 6, 5, 13, 19, 45, 921, DateTimeKind.Local).AddTicks(2837),
                            UserId = 1
                        },
                        new
                        {
                            Id = 14,
                            CreatedAt = new DateTime(2026, 6, 5, 13, 19, 45, 921, DateTimeKind.Local).AddTicks(2838),
                            ModuleId = 14,
                            RolId = 1,
                            UpdatedAt = new DateTime(2026, 6, 5, 13, 19, 45, 921, DateTimeKind.Local).AddTicks(2839),
                            UserId = 1
                        },
                        new
                        {
                            Id = 15,
                            CreatedAt = new DateTime(2026, 6, 5, 13, 19, 45, 921, DateTimeKind.Local).AddTicks(2840),
                            ModuleId = 15,
                            RolId = 1,
                            UpdatedAt = new DateTime(2026, 6, 5, 13, 19, 45, 921, DateTimeKind.Local).AddTicks(2840),
                            UserId = 1
                        },
                        new
                        {
                            Id = 16,
                            CreatedAt = new DateTime(2026, 6, 5, 13, 19, 45, 921, DateTimeKind.Local).AddTicks(2841),
                            ModuleId = 16,
                            RolId = 1,
                            UpdatedAt = new DateTime(2026, 6, 5, 13, 19, 45, 921, DateTimeKind.Local).AddTicks(2842),
                            UserId = 1
                        },
                        new
                        {
                            Id = 17,
                            CreatedAt = new DateTime(2026, 6, 5, 13, 19, 45, 921, DateTimeKind.Local).AddTicks(2844),
                            ModuleId = 17,
                            RolId = 1,
                            UpdatedAt = new DateTime(2026, 6, 5, 13, 19, 45, 921, DateTimeKind.Local).AddTicks(2844),
                            UserId = 1
                        },
                        new
                        {
                            Id = 18,
                            CreatedAt = new DateTime(2026, 6, 5, 13, 19, 45, 921, DateTimeKind.Local).AddTicks(2845),
                            ModuleId = 18,
                            RolId = 1,
                            UpdatedAt = new DateTime(2026, 6, 5, 13, 19, 45, 921, DateTimeKind.Local).AddTicks(2846),
                            UserId = 1
                        },
                        new
                        {
                            Id = 19,
                            CreatedAt = new DateTime(2026, 6, 5, 13, 19, 45, 921, DateTimeKind.Local).AddTicks(2847),
                            ModuleId = 19,
                            RolId = 1,
                            UpdatedAt = new DateTime(2026, 6, 5, 13, 19, 45, 921, DateTimeKind.Local).AddTicks(2847),
                            UserId = 1
                        },
                        new
                        {
                            Id = 20,
                            CreatedAt = new DateTime(2026, 6, 5, 13, 19, 45, 921, DateTimeKind.Local).AddTicks(2848),
                            ModuleId = 20,
                            RolId = 1,
                            UpdatedAt = new DateTime(2026, 6, 5, 13, 19, 45, 921, DateTimeKind.Local).AddTicks(2848),
                            UserId = 1
                        },
                        new
                        {
                            Id = 21,
                            CreatedAt = new DateTime(2026, 6, 5, 13, 19, 45, 921, DateTimeKind.Local).AddTicks(2849),
                            ModuleId = 21,
                            RolId = 1,
                            UpdatedAt = new DateTime(2026, 6, 5, 13, 19, 45, 921, DateTimeKind.Local).AddTicks(2850),
                            UserId = 1
                        },
                        new
                        {
                            Id = 22,
                            CreatedAt = new DateTime(2026, 6, 5, 13, 19, 45, 921, DateTimeKind.Local).AddTicks(2851),
                            ModuleId = 22,
                            RolId = 1,
                            UpdatedAt = new DateTime(2026, 6, 5, 13, 19, 45, 921, DateTimeKind.Local).AddTicks(2851),
                            UserId = 1
                        },
                        new
                        {
                            Id = 23,
                            CreatedAt = new DateTime(2026, 6, 5, 13, 19, 45, 921, DateTimeKind.Local).AddTicks(2852),
                            ModuleId = 23,
                            RolId = 1,
                            UpdatedAt = new DateTime(2026, 6, 5, 13, 19, 45, 921, DateTimeKind.Local).AddTicks(2852),
                            UserId = 1
                        },
                        new
                        {
                            Id = 24,
                            CreatedAt = new DateTime(2026, 6, 5, 13, 19, 45, 921, DateTimeKind.Local).AddTicks(2853),
                            ModuleId = 24,
                            RolId = 1,
                            UpdatedAt = new DateTime(2026, 6, 5, 13, 19, 45, 921, DateTimeKind.Local).AddTicks(2854),
                            UserId = 1
                        },
                        new
                        {
                            Id = 25,
                            CreatedAt = new DateTime(2026, 6, 5, 13, 19, 45, 921, DateTimeKind.Local).AddTicks(2855),
                            ModuleId = 25,
                            RolId = 1,
                            UpdatedAt = new DateTime(2026, 6, 5, 13, 19, 45, 921, DateTimeKind.Local).AddTicks(2855),
                            UserId = 1
                        },
                        new
                        {
                            Id = 26,
                            CreatedAt = new DateTime(2026, 6, 5, 13, 19, 45, 921, DateTimeKind.Local).AddTicks(3018),
                            ModuleId = 26,
                            RolId = 1,
                            UpdatedAt = new DateTime(2026, 6, 5, 13, 19, 45, 921, DateTimeKind.Local).AddTicks(3019),
                            UserId = 1
                        },
                        new
                        {
                            Id = 27,
                            CreatedAt = new DateTime(2026, 6, 5, 13, 19, 45, 921, DateTimeKind.Local).AddTicks(3020),
                            ModuleId = 27,
                            RolId = 1,
                            UpdatedAt = new DateTime(2026, 6, 5, 13, 19, 45, 921, DateTimeKind.Local).AddTicks(3021),
                            UserId = 1
                        },
                        new
                        {
                            Id = 28,
                            CreatedAt = new DateTime(2026, 6, 5, 13, 19, 45, 921, DateTimeKind.Local).AddTicks(3022),
                            ModuleId = 28,
                            RolId = 1,
                            UpdatedAt = new DateTime(2026, 6, 5, 13, 19, 45, 921, DateTimeKind.Local).AddTicks(3022),
                            UserId = 1
                        });
                });

            modelBuilder.Entity("Entity.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Message")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("Entity.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 6, 5, 13, 19, 45, 921, DateTimeKind.Local).AddTicks(1672),
                            Name = "Süper Admin",
                            UpdatedAt = new DateTime(2026, 6, 5, 13, 19, 45, 921, DateTimeKind.Local).AddTicks(1685)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 6, 5, 13, 19, 45, 921, DateTimeKind.Local).AddTicks(1687),
                            Name = "Kullanıcı",
                            UpdatedAt = new DateTime(2026, 6, 5, 13, 19, 45, 921, DateTimeKind.Local).AddTicks(1687)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 6, 5, 13, 19, 45, 921, DateTimeKind.Local).AddTicks(1688),
                            Name = "Demo",
                            UpdatedAt = new DateTime(2026, 6, 5, 13, 19, 45, 921, DateTimeKind.Local).AddTicks(1689)
                        });
                });

            modelBuilder.Entity("Entity.Soru", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<List<Dictionary<string, string>>>("Cevaplar")
                        .HasColumnType("jsonb");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Dictionary<string, string>>("DogruCevap")
                        .HasColumnType("jsonb");

                    b.Property<string>("Hedef")
                        .HasColumnType("text");

                    b.Property<string>("OlcekMaddesi")
                        .HasColumnType("text");

                    b.Property<string>("SoruMetni")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("VideoPath")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Sorus");
                });

            modelBuilder.Entity("Entity.SoruUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("Puan")
                        .HasColumnType("integer");

                    b.Property<int>("SoruId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<string>("VerilenCevap")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("SoruId");

                    b.HasIndex("UserId");

                    b.ToTable("SoruUsers");
                });

            modelBuilder.Entity("Entity.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("CozumlemeTamamlandiMi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("DeviceToken")
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .HasColumnType("text");

                    b.Property<bool>("IlkGiris")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<bool>("KvkkApproved")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("OgrenciNo")
                        .HasColumnType("text");

                    b.Property<bool>("OnamApproved")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<byte[]>("PasswordHash")
                        .HasColumnType("bytea");

                    b.Property<byte[]>("PasswordSalt")
                        .HasColumnType("bytea");

                    b.Property<string>("Phone")
                        .HasColumnType("text");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.Property<bool>("SimulasyonTamamlandiMi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Surname")
                        .HasColumnType("text");

                    b.Property<int?>("ToplamPuan")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("UserName")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CozumlemeTamamlandiMi = false,
                            IlkGiris = false,
                            KvkkApproved = false,
                            OnamApproved = false,
                            PasswordHash = new byte[] { 43, 142, 144, 18, 187, 111, 10, 75, 252, 141, 0, 112, 140, 177, 217, 68, 232, 82, 60, 172, 149, 8, 244, 88, 40, 105, 134, 152, 19, 237, 158, 250, 134, 224, 237, 94, 243, 26, 220, 95, 3, 46, 216, 178, 77, 109, 166, 242, 152, 73, 18, 13, 146, 103, 248, 9, 69, 61, 216, 30, 82, 92, 102, 105 },
                            PasswordSalt = new byte[] { 21, 59, 203, 84, 204, 11, 65, 99, 179, 118, 220, 170, 161, 23, 99, 240, 119, 242, 4, 72, 103, 231, 19, 174, 225, 59, 161, 75, 163, 5, 102, 34, 49, 255, 166, 192, 225, 230, 82, 120, 87, 134, 255, 231, 138, 28, 61, 161, 152, 199, 243, 214, 97, 176, 159, 241, 53, 244, 222, 102, 142, 64, 159, 101, 62, 241, 208, 175, 215, 7, 42, 36, 115, 189, 62, 106, 245, 102, 174, 249, 237, 233, 169, 30, 0, 78, 224, 24, 89, 80, 21, 203, 18, 242, 125, 160, 119, 177, 241, 180, 34, 206, 241, 3, 113, 148, 182, 99, 107, 50, 170, 223, 161, 196, 172, 215, 47, 20, 48, 229, 204, 4, 222, 75, 142, 117, 66, 140 },
                            Phone = "00000000000",
                            RoleId = 1,
                            SimulasyonTamamlandiMi = false
                        });
                });

            modelBuilder.Entity("Entity.CozumlemeSoruUser", b =>
                {
                    b.HasOne("Entity.User", "User")
                        .WithMany("CozumlemeSoruUsers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Entity.ModuleRoles", b =>
                {
                    b.HasOne("Entity.Module", "Module")
                        .WithMany("ModuleRoles")
                        .HasForeignKey("ModuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entity.Role", "Role")
                        .WithMany("ModuleRoles")
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entity.User", "User")
                        .WithMany("ModuleRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Module");

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Entity.SoruUser", b =>
                {
                    b.HasOne("Entity.Soru", "Soru")
                        .WithMany("SoruUsers")
                        .HasForeignKey("SoruId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entity.User", "User")
                        .WithMany("SoruUsers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Soru");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Entity.User", b =>
                {
                    b.HasOne("Entity.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Entity.Module", b =>
                {
                    b.Navigation("ModuleRoles");
                });

            modelBuilder.Entity("Entity.Role", b =>
                {
                    b.Navigation("ModuleRoles");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("Entity.Soru", b =>
                {
                    b.Navigation("SoruUsers");
                });

            modelBuilder.Entity("Entity.User", b =>
                {
                    b.Navigation("CozumlemeSoruUsers");

                    b.Navigation("ModuleRoles");

                    b.Navigation("SoruUsers");
                });
#pragma warning restore 612, 618
        }
    }
}
